<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore"
    name="subpackages"
    nsURI="https://plortinus.github.io/model2blockly/examples/subpackages"
    nsPrefix="subpackages">

  <eAnnotations source="blockly">
    <details key="workspace.renderer" value="zelos"/>
    <details key="workspace.trashcan" value="true"/>
    <details key="workspace.zoom.controls" value="true"/>
    <details key="workspace.zoom.wheel" value="true"/>
    <details key="workspace.move.scrollbars" value="true"/>
    <details key="workspace.move.drag" value="true"/>

  </eAnnotations>


  <eClassifiers xsi:type="ecore:EClass" name="Dashboard">
    <eAnnotations source="blockly">
      <details key="colour" value="260"/>
      <details key="category" value="Root"/>
      <details key="inputsInline" value="true"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="title"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="Metrics"/>
  </eClassifiers>

  <eSubpackages name="controls"
      nsURI="https://plortinus.github.io/model2blockly/examples/subpackages/controls"
      nsPrefix="controls">
    <eClassifiers xsi:type="ecore:EClass" name="Chart">
      <eAnnotations source="blockly">
        <details key="colour" value="160"/>
        <details key="category" value="Subpackage"/>
        <details key="inputsInline" value="true"/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="series"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          defaultValueLiteral="revenue"/>
    </eClassifiers>
  </eSubpackages>

</ecore:EPackage>
