/*
 * generated by Xtext 2.42.0
 */
package io.github.plortinus.model2blockly.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import io.github.plortinus.model2blockly.ide.contentassist.antlr.internal.InternalModel2BlocklyParser;
import io.github.plortinus.model2blockly.services.Model2BlocklyGrammarAccess;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;

public class Model2BlocklyParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(Model2BlocklyGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, Model2BlocklyGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getFeatureAccess().getAlternatives(), "rule__Feature__Alternatives");
			builder.put(grammarAccess.getUiOptionsAccess().getAlternatives(), "rule__UiOptions__Alternatives");
			builder.put(grammarAccess.getAttributeTypeAccess().getAlternatives(), "rule__AttributeType__Alternatives");
			builder.put(grammarAccess.getWorkspaceOptionAccess().getAlternatives(), "rule__WorkspaceOption__Alternatives");
			builder.put(grammarAccess.getUiWidgetAccess().getAlternatives(), "rule__UiWidget__Alternatives");
			builder.put(grammarAccess.getUiVariantAccess().getAlternatives(), "rule__UiVariant__Alternatives");
			builder.put(grammarAccess.getSimpleTypeNameAccess().getAlternatives(), "rule__SimpleTypeName__Alternatives");
			builder.put(grammarAccess.getValidationKindAccess().getAlternatives(), "rule__ValidationKind__Alternatives");
			builder.put(grammarAccess.getBoolValAccess().getAlternatives(), "rule__BoolVal__Alternatives");
			builder.put(grammarAccess.getDomainModelAccess().getGroup(), "rule__DomainModel__Group__0");
			builder.put(grammarAccess.getDomainModelAccess().getGroup_2(), "rule__DomainModel__Group_2__0");
			builder.put(grammarAccess.getDomainModelAccess().getGroup_3(), "rule__DomainModel__Group_3__0");
			builder.put(grammarAccess.getDomainModelAccess().getGroup_4(), "rule__DomainModel__Group_4__0");
			builder.put(grammarAccess.getCategoryDefAccess().getGroup(), "rule__CategoryDef__Group__0");
			builder.put(grammarAccess.getCategoryDefAccess().getGroup_2(), "rule__CategoryDef__Group_2__0");
			builder.put(grammarAccess.getCategoryDefAccess().getGroup_3(), "rule__CategoryDef__Group_3__0");
			builder.put(grammarAccess.getCategoryDefAccess().getGroup_4(), "rule__CategoryDef__Group_4__0");
			builder.put(grammarAccess.getClassDefAccess().getGroup(), "rule__ClassDef__Group__0");
			builder.put(grammarAccess.getClassDefAccess().getGroup_1(), "rule__ClassDef__Group_1__0");
			builder.put(grammarAccess.getClassDefAccess().getGroup_1_1(), "rule__ClassDef__Group_1_1__0");
			builder.put(grammarAccess.getClassDefAccess().getGroup_4(), "rule__ClassDef__Group_4__0");
			builder.put(grammarAccess.getClassDefAccess().getGroup_5(), "rule__ClassDef__Group_5__0");
			builder.put(grammarAccess.getClassDefAccess().getGroup_6(), "rule__ClassDef__Group_6__0");
			builder.put(grammarAccess.getClassDefAccess().getGroup_7(), "rule__ClassDef__Group_7__0");
			builder.put(grammarAccess.getClassDefAccess().getGroup_8(), "rule__ClassDef__Group_8__0");
			builder.put(grammarAccess.getClassDefAccess().getGroup_9(), "rule__ClassDef__Group_9__0");
			builder.put(grammarAccess.getClassDefAccess().getGroup_10(), "rule__ClassDef__Group_10__0");
			builder.put(grammarAccess.getClassDefAccess().getGroup_11(), "rule__ClassDef__Group_11__0");
			builder.put(grammarAccess.getClassDefAccess().getGroup_13(), "rule__ClassDef__Group_13__0");
			builder.put(grammarAccess.getAttributeAccess().getGroup(), "rule__Attribute__Group__0");
			builder.put(grammarAccess.getAttributeAccess().getGroup_5(), "rule__Attribute__Group_5__0");
			builder.put(grammarAccess.getAttributeAccess().getGroup_6(), "rule__Attribute__Group_6__0");
			builder.put(grammarAccess.getAttributeAccess().getGroup_7(), "rule__Attribute__Group_7__0");
			builder.put(grammarAccess.getAttributeAccess().getGroup_8(), "rule__Attribute__Group_8__0");
			builder.put(grammarAccess.getAttributeAccess().getGroup_9(), "rule__Attribute__Group_9__0");
			builder.put(grammarAccess.getAttributeAccess().getGroup_10(), "rule__Attribute__Group_10__0");
			builder.put(grammarAccess.getAttributeAccess().getGroup_11(), "rule__Attribute__Group_11__0");
			builder.put(grammarAccess.getContainmentAccess().getGroup(), "rule__Containment__Group__0");
			builder.put(grammarAccess.getContainmentAccess().getGroup_3(), "rule__Containment__Group_3__0");
			builder.put(grammarAccess.getReferenceAccess().getGroup(), "rule__Reference__Group__0");
			builder.put(grammarAccess.getReferenceAccess().getGroup_4(), "rule__Reference__Group_4__0");
			builder.put(grammarAccess.getValueInputAccess().getGroup(), "rule__ValueInput__Group__0");
			builder.put(grammarAccess.getValueInputAccess().getGroup_3(), "rule__ValueInput__Group_3__0");
			builder.put(grammarAccess.getCardinalityAccess().getGroup(), "rule__Cardinality__Group__0");
			builder.put(grammarAccess.getUiOptionsAccess().getGroup_0(), "rule__UiOptions__Group_0__0");
			builder.put(grammarAccess.getUiOptionsAccess().getGroup_1(), "rule__UiOptions__Group_1__0");
			builder.put(grammarAccess.getUiOptionsAccess().getGroup_2(), "rule__UiOptions__Group_2__0");
			builder.put(grammarAccess.getUiOptionsAccess().getGroup_3(), "rule__UiOptions__Group_3__0");
			builder.put(grammarAccess.getUiOptionsAccess().getGroup_4(), "rule__UiOptions__Group_4__0");
			builder.put(grammarAccess.getUiOptionsAccess().getGroup_5(), "rule__UiOptions__Group_5__0");
			builder.put(grammarAccess.getUiOptionsAccess().getGroup_8(), "rule__UiOptions__Group_8__0");
			builder.put(grammarAccess.getUiOptionsAccess().getGroup_9(), "rule__UiOptions__Group_9__0");
			builder.put(grammarAccess.getEnumTypeAccess().getGroup(), "rule__EnumType__Group__0");
			builder.put(grammarAccess.getEnumTypeAccess().getGroup_3(), "rule__EnumType__Group_3__0");
			builder.put(grammarAccess.getEnumLiteralAccess().getGroup(), "rule__EnumLiteral__Group__0");
			builder.put(grammarAccess.getEnumLiteralAccess().getGroup_1(), "rule__EnumLiteral__Group_1__0");
			builder.put(grammarAccess.getConstraintDefAccess().getGroup(), "rule__ConstraintDef__Group__0");
			builder.put(grammarAccess.getValidationDefAccess().getGroup(), "rule__ValidationDef__Group__0");
			builder.put(grammarAccess.getValidationDefAccess().getGroup_7(), "rule__ValidationDef__Group_7__0");
			builder.put(grammarAccess.getWorkspaceConfigAccess().getGroup(), "rule__WorkspaceConfig__Group__0");
			builder.put(grammarAccess.getStringOptionAccess().getGroup(), "rule__StringOption__Group__0");
			builder.put(grammarAccess.getIntOptionAccess().getGroup(), "rule__IntOption__Group__0");
			builder.put(grammarAccess.getBoolOptionAccess().getGroup(), "rule__BoolOption__Group__0");
			builder.put(grammarAccess.getObjectOptionAccess().getGroup(), "rule__ObjectOption__Group__0");
			builder.put(grammarAccess.getDomainModelAccess().getNameAssignment_1(), "rule__DomainModel__NameAssignment_1");
			builder.put(grammarAccess.getDomainModelAccess().getCodeLanguageAssignment_2_1(), "rule__DomainModel__CodeLanguageAssignment_2_1");
			builder.put(grammarAccess.getDomainModelAccess().getCodeFileExtensionAssignment_3_1(), "rule__DomainModel__CodeFileExtensionAssignment_3_1");
			builder.put(grammarAccess.getDomainModelAccess().getRuntimeKindAssignment_4_1(), "rule__DomainModel__RuntimeKindAssignment_4_1");
			builder.put(grammarAccess.getDomainModelAccess().getWorkspaceAssignment_5(), "rule__DomainModel__WorkspaceAssignment_5");
			builder.put(grammarAccess.getDomainModelAccess().getCategoriesAssignment_6(), "rule__DomainModel__CategoriesAssignment_6");
			builder.put(grammarAccess.getDomainModelAccess().getClassesAssignment_7(), "rule__DomainModel__ClassesAssignment_7");
			builder.put(grammarAccess.getDomainModelAccess().getConstraintsAssignment_8(), "rule__DomainModel__ConstraintsAssignment_8");
			builder.put(grammarAccess.getDomainModelAccess().getValidationsAssignment_9(), "rule__DomainModel__ValidationsAssignment_9");
			builder.put(grammarAccess.getCategoryDefAccess().getNameAssignment_1(), "rule__CategoryDef__NameAssignment_1");
			builder.put(grammarAccess.getCategoryDefAccess().getLabelAssignment_2_1(), "rule__CategoryDef__LabelAssignment_2_1");
			builder.put(grammarAccess.getCategoryDefAccess().getColourAssignment_3_1(), "rule__CategoryDef__ColourAssignment_3_1");
			builder.put(grammarAccess.getCategoryDefAccess().getSubcategoriesAssignment_4_1(), "rule__CategoryDef__SubcategoriesAssignment_4_1");
			builder.put(grammarAccess.getClassDefAccess().getAbstractAssignment_0(), "rule__ClassDef__AbstractAssignment_0");
			builder.put(grammarAccess.getClassDefAccess().getOutputAssignment_1_0(), "rule__ClassDef__OutputAssignment_1_0");
			builder.put(grammarAccess.getClassDefAccess().getOutputTypeAssignment_1_1_1(), "rule__ClassDef__OutputTypeAssignment_1_1_1");
			builder.put(grammarAccess.getClassDefAccess().getNameAssignment_3(), "rule__ClassDef__NameAssignment_3");
			builder.put(grammarAccess.getClassDefAccess().getSuperClassAssignment_4_1(), "rule__ClassDef__SuperClassAssignment_4_1");
			builder.put(grammarAccess.getClassDefAccess().getCategoryAssignment_5_1(), "rule__ClassDef__CategoryAssignment_5_1");
			builder.put(grammarAccess.getClassDefAccess().getColourAssignment_6_1(), "rule__ClassDef__ColourAssignment_6_1");
			builder.put(grammarAccess.getClassDefAccess().getLabelAssignment_7_1(), "rule__ClassDef__LabelAssignment_7_1");
			builder.put(grammarAccess.getClassDefAccess().getMessage0Assignment_8_1(), "rule__ClassDef__Message0Assignment_8_1");
			builder.put(grammarAccess.getClassDefAccess().getTooltipAssignment_9_1(), "rule__ClassDef__TooltipAssignment_9_1");
			builder.put(grammarAccess.getClassDefAccess().getHelpUrlAssignment_10_1(), "rule__ClassDef__HelpUrlAssignment_10_1");
			builder.put(grammarAccess.getClassDefAccess().getInputsInlineAssignment_11_1(), "rule__ClassDef__InputsInlineAssignment_11_1");
			builder.put(grammarAccess.getClassDefAccess().getInlineAssignment_12(), "rule__ClassDef__InlineAssignment_12");
			builder.put(grammarAccess.getClassDefAccess().getCodeTemplateAssignment_13_1(), "rule__ClassDef__CodeTemplateAssignment_13_1");
			builder.put(grammarAccess.getClassDefAccess().getFeaturesAssignment_15(), "rule__ClassDef__FeaturesAssignment_15");
			builder.put(grammarAccess.getAttributeAccess().getNameAssignment_1(), "rule__Attribute__NameAssignment_1");
			builder.put(grammarAccess.getAttributeAccess().getTypeAssignment_3(), "rule__Attribute__TypeAssignment_3");
			builder.put(grammarAccess.getAttributeAccess().getCardinalityAssignment_4(), "rule__Attribute__CardinalityAssignment_4");
			builder.put(grammarAccess.getAttributeAccess().getDefaultValueAssignment_5_1(), "rule__Attribute__DefaultValueAssignment_5_1");
			builder.put(grammarAccess.getAttributeAccess().getMinAssignment_6_1(), "rule__Attribute__MinAssignment_6_1");
			builder.put(grammarAccess.getAttributeAccess().getMaxAssignment_7_1(), "rule__Attribute__MaxAssignment_7_1");
			builder.put(grammarAccess.getAttributeAccess().getImageUrlAssignment_8_1(), "rule__Attribute__ImageUrlAssignment_8_1");
			builder.put(grammarAccess.getAttributeAccess().getImageWidthAssignment_9_1(), "rule__Attribute__ImageWidthAssignment_9_1");
			builder.put(grammarAccess.getAttributeAccess().getImageHeightAssignment_10_1(), "rule__Attribute__ImageHeightAssignment_10_1");
			builder.put(grammarAccess.getAttributeAccess().getImageAltAssignment_11_1(), "rule__Attribute__ImageAltAssignment_11_1");
			builder.put(grammarAccess.getAttributeAccess().getRequiredAssignment_12(), "rule__Attribute__RequiredAssignment_12");
			builder.put(grammarAccess.getAttributeAccess().getIdAssignment_13(), "rule__Attribute__IdAssignment_13");
			builder.put(grammarAccess.getAttributeAccess().getUniqueAssignment_14(), "rule__Attribute__UniqueAssignment_14");
			builder.put(grammarAccess.getAttributeAccess().getNonUniqueAssignment_15(), "rule__Attribute__NonUniqueAssignment_15");
			builder.put(grammarAccess.getAttributeAccess().getOrderedAssignment_16(), "rule__Attribute__OrderedAssignment_16");
			builder.put(grammarAccess.getAttributeAccess().getUnorderedAssignment_17(), "rule__Attribute__UnorderedAssignment_17");
			builder.put(grammarAccess.getAttributeAccess().getUiAssignment_18(), "rule__Attribute__UiAssignment_18");
			builder.put(grammarAccess.getContainmentAccess().getTypeAssignment_1(), "rule__Containment__TypeAssignment_1");
			builder.put(grammarAccess.getContainmentAccess().getNameAssignment_2(), "rule__Containment__NameAssignment_2");
			builder.put(grammarAccess.getContainmentAccess().getLowerAssignment_3_1(), "rule__Containment__LowerAssignment_3_1");
			builder.put(grammarAccess.getContainmentAccess().getUpperAssignment_3_3(), "rule__Containment__UpperAssignment_3_3");
			builder.put(grammarAccess.getContainmentAccess().getUiAssignment_4(), "rule__Containment__UiAssignment_4");
			builder.put(grammarAccess.getReferenceAccess().getTypeAssignment_1(), "rule__Reference__TypeAssignment_1");
			builder.put(grammarAccess.getReferenceAccess().getNameAssignment_2(), "rule__Reference__NameAssignment_2");
			builder.put(grammarAccess.getReferenceAccess().getCardinalityAssignment_3(), "rule__Reference__CardinalityAssignment_3");
			builder.put(grammarAccess.getReferenceAccess().getOppositeNameAssignment_4_1(), "rule__Reference__OppositeNameAssignment_4_1");
			builder.put(grammarAccess.getReferenceAccess().getRequiredAssignment_5(), "rule__Reference__RequiredAssignment_5");
			builder.put(grammarAccess.getReferenceAccess().getUniqueAssignment_6(), "rule__Reference__UniqueAssignment_6");
			builder.put(grammarAccess.getReferenceAccess().getNonUniqueAssignment_7(), "rule__Reference__NonUniqueAssignment_7");
			builder.put(grammarAccess.getReferenceAccess().getOrderedAssignment_8(), "rule__Reference__OrderedAssignment_8");
			builder.put(grammarAccess.getReferenceAccess().getUnorderedAssignment_9(), "rule__Reference__UnorderedAssignment_9");
			builder.put(grammarAccess.getReferenceAccess().getUiAssignment_10(), "rule__Reference__UiAssignment_10");
			builder.put(grammarAccess.getValueInputAccess().getTypeAssignment_1(), "rule__ValueInput__TypeAssignment_1");
			builder.put(grammarAccess.getValueInputAccess().getNameAssignment_2(), "rule__ValueInput__NameAssignment_2");
			builder.put(grammarAccess.getValueInputAccess().getShadowTypeAssignment_3_1(), "rule__ValueInput__ShadowTypeAssignment_3_1");
			builder.put(grammarAccess.getValueInputAccess().getUiAssignment_4(), "rule__ValueInput__UiAssignment_4");
			builder.put(grammarAccess.getCardinalityAccess().getLowerAssignment_1(), "rule__Cardinality__LowerAssignment_1");
			builder.put(grammarAccess.getCardinalityAccess().getUpperAssignment_3(), "rule__Cardinality__UpperAssignment_3");
			builder.put(grammarAccess.getUiOptionsAccess().getWidgetAssignment_0_1(), "rule__UiOptions__WidgetAssignment_0_1");
			builder.put(grammarAccess.getUiOptionsAccess().getUiLabelAssignment_1_1(), "rule__UiOptions__UiLabelAssignment_1_1");
			builder.put(grammarAccess.getUiOptionsAccess().getHelpAssignment_2_1(), "rule__UiOptions__HelpAssignment_2_1");
			builder.put(grammarAccess.getUiOptionsAccess().getPlaceholderAssignment_3_1(), "rule__UiOptions__PlaceholderAssignment_3_1");
			builder.put(grammarAccess.getUiOptionsAccess().getGroupAssignment_4_1(), "rule__UiOptions__GroupAssignment_4_1");
			builder.put(grammarAccess.getUiOptionsAccess().getOrderAssignment_5_1(), "rule__UiOptions__OrderAssignment_5_1");
			builder.put(grammarAccess.getUiOptionsAccess().getUiReadonlyAssignment_6(), "rule__UiOptions__UiReadonlyAssignment_6");
			builder.put(grammarAccess.getUiOptionsAccess().getUiHiddenAssignment_7(), "rule__UiOptions__UiHiddenAssignment_7");
			builder.put(grammarAccess.getUiOptionsAccess().getVariantAssignment_8_1(), "rule__UiOptions__VariantAssignment_8_1");
			builder.put(grammarAccess.getUiOptionsAccess().getReferenceLabelFieldAssignment_9_1(), "rule__UiOptions__ReferenceLabelFieldAssignment_9_1");
			builder.put(grammarAccess.getSimpleTypeAccess().getTypeNameAssignment(), "rule__SimpleType__TypeNameAssignment");
			builder.put(grammarAccess.getEnumTypeAccess().getLiteralsAssignment_2(), "rule__EnumType__LiteralsAssignment_2");
			builder.put(grammarAccess.getEnumTypeAccess().getLiteralsAssignment_3_1(), "rule__EnumType__LiteralsAssignment_3_1");
			builder.put(grammarAccess.getEnumLiteralAccess().getNameAssignment_0(), "rule__EnumLiteral__NameAssignment_0");
			builder.put(grammarAccess.getEnumLiteralAccess().getLabelAssignment_1_1(), "rule__EnumLiteral__LabelAssignment_1_1");
			builder.put(grammarAccess.getConstraintDefAccess().getNameAssignment_1(), "rule__ConstraintDef__NameAssignment_1");
			builder.put(grammarAccess.getConstraintDefAccess().getTargetAssignment_3(), "rule__ConstraintDef__TargetAssignment_3");
			builder.put(grammarAccess.getConstraintDefAccess().getPredecessorAssignment_7(), "rule__ConstraintDef__PredecessorAssignment_7");
			builder.put(grammarAccess.getValidationDefAccess().getNameAssignment_1(), "rule__ValidationDef__NameAssignment_1");
			builder.put(grammarAccess.getValidationDefAccess().getTargetAssignment_3(), "rule__ValidationDef__TargetAssignment_3");
			builder.put(grammarAccess.getValidationDefAccess().getKindAssignment_5(), "rule__ValidationDef__KindAssignment_5");
			builder.put(grammarAccess.getValidationDefAccess().getExpressionAssignment_6(), "rule__ValidationDef__ExpressionAssignment_6");
			builder.put(grammarAccess.getValidationDefAccess().getMessageAssignment_7_1(), "rule__ValidationDef__MessageAssignment_7_1");
			builder.put(grammarAccess.getWorkspaceConfigAccess().getOptionsAssignment_2(), "rule__WorkspaceConfig__OptionsAssignment_2");
			builder.put(grammarAccess.getStringOptionAccess().getKeyAssignment_0(), "rule__StringOption__KeyAssignment_0");
			builder.put(grammarAccess.getStringOptionAccess().getValueAssignment_2(), "rule__StringOption__ValueAssignment_2");
			builder.put(grammarAccess.getIntOptionAccess().getKeyAssignment_0(), "rule__IntOption__KeyAssignment_0");
			builder.put(grammarAccess.getIntOptionAccess().getValueAssignment_2(), "rule__IntOption__ValueAssignment_2");
			builder.put(grammarAccess.getBoolOptionAccess().getKeyAssignment_0(), "rule__BoolOption__KeyAssignment_0");
			builder.put(grammarAccess.getBoolOptionAccess().getValueAssignment_2(), "rule__BoolOption__ValueAssignment_2");
			builder.put(grammarAccess.getObjectOptionAccess().getKeyAssignment_0(), "rule__ObjectOption__KeyAssignment_0");
			builder.put(grammarAccess.getObjectOptionAccess().getEntriesAssignment_3(), "rule__ObjectOption__EntriesAssignment_3");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private Model2BlocklyGrammarAccess grammarAccess;

	@Override
	protected InternalModel2BlocklyParser createParser() {
		InternalModel2BlocklyParser result = new InternalModel2BlocklyParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public Model2BlocklyGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(Model2BlocklyGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
