<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore"
    name="relations"
    nsURI="http://www.example.org/relations"
    nsPrefix="relations">

  <eClassifiers xsi:type="ecore:EClass" name="Workflow">
    <eAnnotations source="blockly">
      <details key="colour" value="260"/>
      <details key="category" value="Relations"/>
      <details key="inputsInline" value="false"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="Review workflow"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elements"
        lowerBound="1" upperBound="6" eType="#//Element" containment="true">
      <eAnnotations source="ui">
        <details key="widget" value="slot"/>
        <details key="label" value="Elements"/>
        <details key="order" value="2"/>
        <details key="variant" value="default"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EClass" name="Element" abstract="true">
    <eAnnotations source="blockly">
      <details key="colour" value="120"/>
      <details key="category" value="Relations"/>
      <details key="inputsInline" value="false"/>
    </eAnnotations>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EClass" name="Card" eSuperTypes="#//Element">
    <eAnnotations source="blockly">
      <details key="colour" value="120"/>
      <details key="category" value="Relations"/>
      <details key="inputsInline" value="false"/>
    </eAnnotations>

    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cardId"
        iD="true" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="card-1"/>

    <eStructuralFeatures xsi:type="ecore:EReference" name="content"
        eType="#//TextExpression" containment="true">
      <eAnnotations source="blockly">
        <details key="type" value="input_value"/>
        <details key="check" value="TextExpression"/>
        <details key="shadow" value="TextLiteral"/>
      </eAnnotations>
      <eAnnotations source="ui">
        <details key="widget" value="expression-slot"/>
        <details key="label" value="Content"/>
        <details key="order" value="2"/>
        <details key="variant" value="default"/>
      </eAnnotations>
    </eStructuralFeatures>

    <eStructuralFeatures xsi:type="ecore:EAttribute" name="title"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="Review"/>

    <eStructuralFeatures xsi:type="ecore:EReference" name="outgoing"
        upperBound="3" eType="#//Link" eOpposite="#//Link/source">
      <eAnnotations source="ui">
        <details key="widget" value="reference-select"/>
        <details key="label" value="Outgoing links"/>
        <details key="order" value="4"/>
        <details key="variant" value="default"/>
        <details key="referenceLabelField" value="linkId"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EClass" name="Link" eSuperTypes="#//Element">
    <eAnnotations source="blockly">
      <details key="colour" value="120"/>
      <details key="category" value="Relations"/>
      <details key="inputsInline" value="false"/>
    </eAnnotations>

    <eStructuralFeatures xsi:type="ecore:EAttribute" name="linkId"
        iD="true" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="link-1"/>

    <eStructuralFeatures xsi:type="ecore:EReference" name="source"
        lowerBound="1" eType="#//Card" eOpposite="#//Card/outgoing">
      <eAnnotations source="ui">
        <details key="widget" value="reference-select"/>
        <details key="label" value="Source card"/>
        <details key="order" value="2"/>
        <details key="variant" value="default"/>
        <details key="referenceLabelField" value="title"/>
      </eAnnotations>
    </eStructuralFeatures>

    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="Continue"/>

    <eStructuralFeatures xsi:type="ecore:EReference" name="target"
        lowerBound="1" unique="false" ordered="false" eType="#//Card">
      <eAnnotations source="ui">
        <details key="widget" value="reference-select"/>
        <details key="label" value="Target card"/>
        <details key="order" value="4"/>
        <details key="variant" value="default"/>
        <details key="referenceLabelField" value="title"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EClass" name="TextExpression" abstract="true">
    <eAnnotations source="blockly">
      <details key="colour" value="230"/>
      <details key="category" value="Relations"/>
      <details key="output" value="true"/>
      <details key="inputsInline" value="false"/>
    </eAnnotations>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EClass" name="TextLiteral"
      eSuperTypes="#//TextExpression">
    <eAnnotations source="blockly">
      <details key="colour" value="230"/>
      <details key="category" value="Relations"/>
      <details key="output" value="TextExpression"/>
      <details key="inputsInline" value="false"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="textValue"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="Ready"/>
  </eClassifiers>

</ecore:EPackage>
