<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore"
    name="enumdropdown"
    nsURI="https://plortinus.github.io/model2blockly/examples/enumdropdown"
    nsPrefix="enumdropdown">

  <eAnnotations source="blockly">
    <details key="workspace.renderer" value="zelos"/>
    <details key="workspace.trashcan" value="true"/>
    <details key="workspace.zoom.controls" value="true"/>
    <details key="workspace.zoom.wheel" value="true"/>
    <details key="workspace.move.scrollbars" value="true"/>
    <details key="workspace.move.drag" value="true"/>

  </eAnnotations>


  <eClassifiers xsi:type="ecore:EClass" name="Task">
    <eAnnotations source="blockly">
      <details key="colour" value="120"/>
      <details key="category" value="Basics"/>
      <details key="inputsInline" value="true"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="priority"
        eType="#//Priority" defaultValueLiteral="medium">
      <eAnnotations source="ui">
        <details key="label" value="Priority"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EEnum" name="Priority">
    <eLiterals name="low" literal="low"/>
    <eLiterals name="medium" literal="medium"/>
    <eLiterals name="high" literal="high"/>
  </eClassifiers>

</ecore:EPackage>
