<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore"
    name="textfield"
    nsURI="https://plortinus.github.io/model2blockly/examples/textfield"
    nsPrefix="textfield">

  <eAnnotations source="blockly">
    <details key="workspace.renderer" value="zelos"/>
    <details key="workspace.trashcan" value="true"/>
    <details key="workspace.zoom.controls" value="true"/>
    <details key="workspace.zoom.wheel" value="true"/>
    <details key="workspace.move.scrollbars" value="true"/>
    <details key="workspace.move.drag" value="true"/>

  </eAnnotations>


  <eClassifiers xsi:type="ecore:EClass" name="Note">
    <eAnnotations source="blockly">
      <details key="colour" value="210"/>
      <details key="category" value="Basics"/>
      <details key="tooltip" value="A note with a required title."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="title" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="Design note">
      <eAnnotations source="ui">
        <details key="label" value="Title"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>

</ecore:EPackage>
