/*
 * generated by Xtext 2.39.0
 */
package io.github.plortinus.model2blockly.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * Customization of the default outline structure.
 *
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#outline
 */
public class Model2BlocklyOutlineTreeProvider extends DefaultOutlineTreeProvider {

}
