/*
 * generated by Xtext 2.42.0
 */
package io.github.plortinus.model2blockly.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractModel2BlocklyValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(io.github.plortinus.model2blockly.model2Blockly.Model2BlocklyPackage.eINSTANCE);
		return result;
	}
}
