package io.github.plortinus.model2blockly.generator;

import java.util.ArrayList;
import java.util.Collection;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EClassifier;
import org.eclipse.emf.ecore.EAnnotation;
import org.eclipse.emf.ecore.EDataType;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EGenericType;
import org.eclipse.emf.ecore.EOperation;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;
import org.eclipse.emf.ecore.EStructuralFeature;
import org.eclipse.emf.ecore.EAttribute;
import io.github.plortinus.model2blockly.model2Blockly.ClassDef;
import io.github.plortinus.model2blockly.model2Blockly.DomainModel;
import io.github.plortinus.model2blockly.model2Blockly.Feature;
import io.github.plortinus.model2blockly.model2Blockly.Reference;
import io.github.plortinus.model2blockly.intermediate.blocklyspec.BlockTypeSpec;
import io.github.plortinus.model2blockly.intermediate.blocklyspec.EditorSpec;
import io.github.plortinus.model2blockly.intermediate.blocklyspec.ValidationBlockSpec;
import io.github.plortinus.model2blockly.intermediate.blocklyspec.ValidationExpressionSpec;
import io.github.plortinus.model2blockly.intermediate.blocklyspec.ValidationSpec;
import io.github.plortinus.model2blockly.intermediate.blocklyspec.ValidationType;

/**
 * Small Markdown-to-HTML renderer for generated reports.
 *
 * It intentionally supports only the report constructs generated by this
 * project: headings, paragraphs, inline code and pipe tables.
 */
public final class GenerationReportHtmlRenderer {

	private GenerationReportHtmlRenderer() {}

	public static String renderEcoreSummary(EPackage pkg, EditorSpec spec,
			String inputPath, String target, Collection<String> generatedFiles) {
		StringBuilder out = pageStart("Ecore to Blockly Report");
		out.append("<p class=\"lead\">Concise generation report for the Ecore input path.</p>\n");
		appendStats(out, new String[][] {
			{"Input", inputPath},
			{"EPackage", pkg.getName()},
			{"Blocks", String.valueOf(BlocklySpecModelQueries.concreteBlockTypes(spec).size())},
			{"Categories", String.valueOf(spec.getCategories().size())},
			{"Validations", String.valueOf(spec.getValidations().size())},
			{"Target", target}
		});
		appendGenerationPipeline(out, ".ecore", generatedFiles);
		appendEcoreQualitySummary(out, pkg, spec, generatedFiles);
		appendGeneratedFiles(out, generatedFiles);
		appendEcoreNextSteps(out);
		appendEcoreMapping(out, pkg, spec);
		appendEcoreCoverageMatrix(out);
		appendEcoreRecommendations(out, pkg);
		appendEcoreCustomizationHints(out, pkg);
		appendValidationSummary(out, spec);
		appendVisualValidationBlocks(out, spec);
		appendEcoreAttention(out, pkg);
		return pageEnd(out);
	}

	public static String renderModel2BlocklySummary(DomainModel domain, EditorSpec spec,
			String inputPath, Collection<String> generatedFiles) {
		StringBuilder out = pageStart("Model2Blockly Generation Report");
		out.append("<p class=\"lead\">Concise generation report for the textual .model2blockly input path.</p>\n");
		out.append("<p class=\"lead\">Use this page to quickly check what was generated and which modelling decisions affect the editor.</p>\n");
		appendStats(out, new String[][] {
			{"Input", inputPath},
			{"Domain", domain.getName()},
			{"Classes", String.valueOf(domain.getClasses().size())},
			{"Blocks", String.valueOf(BlocklySpecModelQueries.concreteBlockTypes(spec).size())},
			{"Categories", String.valueOf(spec.getCategories().size())},
			{"Validations", String.valueOf(spec.getValidations().size())}
		});
		appendGenerationPipeline(out, ".model2blockly", generatedFiles);
		appendDslQualitySummary(out, spec, generatedFiles);
		appendGeneratedFiles(out, generatedFiles);
		appendDslNextSteps(out);
		appendDslMapping(out, domain, spec);
		appendValidationSummary(out, spec);
		appendVisualValidationBlocks(out, spec);
		appendDslAttention(out, domain);
		return pageEnd(out);
	}

	private static StringBuilder pageStart(String title) {
		StringBuilder out = new StringBuilder();
		out.append("<!doctype html>\n<html lang=\"en\">\n<head>\n");
		out.append("<meta charset=\"utf-8\">\n");
		out.append("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
		out.append("<title>").append(escape(title)).append("</title>\n");
		out.append("<style>\n");
		out.append("""
			:root {
			  color-scheme: light;
			  --bg: #f6f7f9;
			  --panel: #ffffff;
			  --text: #1f252d;
			  --muted: #5f6875;
			  --border: #d9dee5;
			  --header: #eef2f6;
			  --accent: #245a9c;
			  --ok: #176b42;
			  --warn: #8a5a00;
			}
			* { box-sizing: border-box; }
			body {
			  margin: 0;
			  background: var(--bg);
			  color: var(--text);
			  font: 14px/1.55 -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
			}
			main {
			  max-width: 1120px;
			  margin: 0 auto;
			  padding: 32px 24px 56px;
			}
			h1 { margin: 0 0 8px; font-size: 28px; line-height: 1.2; }
			h2 {
			  margin: 30px 0 12px;
			  padding-top: 18px;
			  border-top: 1px solid var(--border);
			  font-size: 19px;
			}
			.lead { max-width: 840px; color: var(--muted); margin: 4px 0; }
			.callout {
			  margin: 18px 0 22px;
			  padding: 14px 16px;
			  border: 1px solid #b9c7d8;
			  border-left: 4px solid var(--accent);
			  border-radius: 8px;
			  background: #f2f6fb;
			}
			.callout h2 {
			  margin: 0 0 8px;
			  padding: 0;
			  border: 0;
			  font-size: 17px;
			}
			.callout ol { margin: 8px 0 0 22px; padding: 0; }
			.callout li { margin: 4px 0; }
			.stats {
			  display: grid;
			  grid-template-columns: repeat(auto-fit, minmax(150px, 1fr));
			  gap: 10px;
			  margin: 20px 0 8px;
			}
			.stat {
			  background: var(--panel);
			  border: 1px solid var(--border);
			  border-radius: 8px;
			  padding: 12px 14px;
			}
			.stat .label { color: var(--muted); font-size: 12px; }
			.stat .value {
			  margin-top: 4px;
			  font-weight: 650;
			  overflow-wrap: anywhere;
			}
			.table-wrap {
			  overflow-x: auto;
			  margin: 12px 0 22px;
			  border: 1px solid var(--border);
			  border-radius: 8px;
			  background: var(--panel);
			}
			table { width: 100%; border-collapse: collapse; min-width: 680px; }
			th, td {
			  padding: 9px 12px;
			  border-bottom: 1px solid var(--border);
			  border-right: 1px solid var(--border);
			  vertical-align: top;
			  text-align: left;
			}
			th:last-child, td:last-child { border-right: 0; }
			tr:last-child td { border-bottom: 0; }
			th { background: var(--header); font-weight: 650; }
			.badge {
			  display: inline-block;
			  padding: 2px 7px;
			  border-radius: 999px;
			  background: #eef1f4;
			  color: #223142;
			  font-size: 12px;
			  font-weight: 600;
			}
			.ok { color: var(--ok); }
			.warn { color: var(--warn); }
			a { color: var(--accent); font-weight: 650; text-decoration: none; }
			a:hover { text-decoration: underline; }
			code {
			  padding: 1px 5px;
			  border-radius: 4px;
			  background: #eef1f4;
			  color: #173b63;
			  font-family: ui-monospace, SFMono-Regular, Menlo, Consolas, monospace;
			  font-size: 0.92em;
			}
			.validation-preview-list {
			  display: grid;
			  gap: 10px;
			  margin: 12px 0 22px;
			}
			.validation-preview {
			  border: 1px solid var(--border);
			  border-radius: 8px;
			  background: var(--panel);
			  overflow: hidden;
			}
			.validation-preview summary {
			  cursor: pointer;
			  padding: 10px 12px;
			  background: var(--header);
			  font-weight: 650;
			}
			.validation-tree { padding: 10px 12px 14px; }
			.validation-node {
			  max-width: 760px;
			  margin: 6px 0;
			  padding: 8px 10px;
			  border: 1px solid var(--border);
			  border-radius: 6px;
			  background: #fff;
			}
			.validation-node-meta {
			  margin-top: 4px;
			  color: var(--muted);
			  font-size: 12px;
			}
			.validation-children {
			  margin-left: 18px;
			  padding-left: 12px;
			  border-left: 2px solid var(--border);
			}
			.validation-edge {
			  margin: 8px 0 2px;
			  color: var(--muted);
			  font-size: 12px;
			  font-weight: 650;
			}
			""");
		out.append("</style>\n</head>\n<body>\n<main>\n");
		out.append("<h1>").append(escape(title)).append("</h1>\n");
		return out;
	}

	private static String pageEnd(StringBuilder out) {
		out.append("</main>\n</body>\n</html>\n");
		return out.toString();
	}

	private static void appendStats(StringBuilder out, String[][] stats) {
		out.append("<section class=\"stats\">\n");
		for (String[] stat : stats) {
			out.append("<div class=\"stat\"><div class=\"label\">")
				.append(escape(stat[0]))
				.append("</div><div class=\"value\">")
				.append(escape(value(stat[1])))
				.append("</div></div>\n");
		}
		out.append("</section>\n");
	}

	private static void appendGeneratedFiles(StringBuilder out, Collection<String> generatedFiles) {
		out.append("<h2>Generated Output</h2>\n");
		tableStart(out, "File", "Purpose");
		for (String file : generatedFiles) {
			if (isKeyOutput(file)) rowLinked(out, file, purpose(file));
		}
		rowLinked(out, "README.md", "✅ Short instructions inside the output folder");
		rowLinked(out, "generation_report.html", "✅ Concise human-readable report");
		tableEnd(out);
	}

	private static boolean isKeyOutput(String file) {
		return isIntermediateXmi(file)
			|| file.endsWith("_standalone.html")
			|| file.endsWith("_editor.html")
			|| file.endsWith("_validations.js")
			|| file.endsWith("_blocks.js")
			|| file.endsWith("validation_workspace.html")
			|| file.endsWith("validation_blocks.json")
			|| file.endsWith("validationBlocks.json")
			|| file.endsWith("validation_runtime.js")
			|| file.endsWith("validationRuntime.js")
			|| file.endsWith("sample_model.json")
			|| file.startsWith("html/");
	}

	private static boolean isIntermediateXmi(String file) {
		return file != null
			&& file.startsWith("intermediate/")
			&& file.endsWith("_blocklyspec.xmi");
	}

	private static String findIntermediateXmi(Collection<String> generatedFiles) {
		for (String file : generatedFiles) {
			if (isIntermediateXmi(file)) return file;
		}
		return null;
	}

	private static void appendGenerationPipeline(StringBuilder out, String sourceKind,
			Collection<String> generatedFiles) {
		String intermediate = findIntermediateXmi(generatedFiles);
		out.append("<h2>Generation Pipeline</h2>\n");
		tableStart(out, "Step", "Artifact", "Meaning");
		row(out, "1. Source model", sourceKind,
			"The selected model is adapted into the shared generator-facing model.");
		row(out, "2. Intermediate EMF model", "EditorSpec",
			"Both the DSL and Ecore routes normalize into the same model shape.");
		rowPipelineLinked(out, "3. Intermediate XMI",
			intermediate != null ? intermediate : "intermediate/*_blocklyspec.xmi",
			intermediate != null
				? "The generator writes this XMI, reloads it, and validates the reloaded model."
				: "The generator writes intermediate XMI, reloads it, and validates the reloaded model.");
		row(out, "4. Blockly editor", "html/*",
			"HTML, JavaScript, validation runtime and report files are emitted from the reloaded EditorSpec model.");
		row(out, "5. Domain instance model", "*_model.xmi",
			"The generated editor can export user-created blocks as EMF-style XMI in the source domain namespace.");
		tableEnd(out);
	}

	private static void appendEcoreQualitySummary(StringBuilder out, EPackage pkg,
			EditorSpec spec, Collection<String> generatedFiles) {
		out.append("<h2>Generation Quality Summary</h2>\n");
		tableStart(out, "Check", "Status", "Meaning");
		row(out, "Editor generated",
			hasStandalone(generatedFiles) ? "✅ Yes" : "❌ No",
			hasStandalone(generatedFiles)
				? "A standalone Blockly editor is available from this report."
				: "No standalone editor was listed in the generated files.");
		row(out, "Sample model generated",
			hasSampleModel(generatedFiles) ? "✅ Yes" : "❌ No",
			hasSampleModel(generatedFiles)
				? "`sample_model.json` and the `Load Sample` button are available."
				: "The user must build the first model manually.");
		row(out, "Sample import support",
			hasStandalone(generatedFiles) && hasSampleModel(generatedFiles) ? "✅ Available" : "❌ Missing",
			"The generated editor embeds the sample model and can load it without file selection.");
		row(out, "Domain instance XMI export",
			hasStandalone(generatedFiles) ? "✅ Available" : "❌ Missing",
			"The generated editor can export created models as EMF-style XMI using EPackage nsURI/nsPrefix metadata.");
		row(out, "Generated validations",
			spec.getValidations().isEmpty() ? "⚠️ None" : "✅ " + spec.getValidations().size(),
			spec.getValidations().isEmpty()
				? "No cardinality, required, uniqueness or expression validations were generated."
				: "Validation rules are generated into the editor runtime.");
		int unsupported = unsupportedEcoreConstructCount(pkg);
		row(out, "Unsupported or partial Ecore constructs",
			unsupported == 0 ? "✅ None detected" : "⚠️ " + unsupported + " detected",
			unsupported == 0
				? "This input does not use the main constructs that remain partial or unsupported."
				: "See `Ecore Coverage Matrix`, `Recommended Improvements` and `What To Check` below.");
		row(out, "EOperations",
			operationCount(pkg) == 0 ? "✅ None detected" : "❌ " + operationCount(pkg) + " not converted",
			operationCount(pkg) == 0
				? "No EOperations need a Blockly behavior mapping."
				: "Operations require an explicit action-block, code-template or extension design.");
		row(out, "Smoke test",
			"▶ Optional",
			"Run `node scripts/smoke-test-generated.mjs` from the repository root to load samples automatically in a browser.");
		tableEnd(out);
	}

	private static void appendDslQualitySummary(StringBuilder out, EditorSpec spec,
			Collection<String> generatedFiles) {
		out.append("<h2>Generation Quality Summary</h2>\n");
		tableStart(out, "Check", "Status", "Meaning");
		row(out, "Editor generated",
			hasStandalone(generatedFiles) ? "✅ Yes" : "❌ No",
			hasStandalone(generatedFiles)
				? "A standalone Blockly editor is available from this report."
				: "No standalone editor was listed in the generated files.");
		row(out, "Sample model generated",
			hasSampleModel(generatedFiles) ? "✅ Yes" : "❌ No",
			hasSampleModel(generatedFiles)
				? "`sample_model.json` and the `Load Sample` button are available."
				: "The user must build the first model manually.");
		row(out, "Sample import support",
			hasStandalone(generatedFiles) && hasSampleModel(generatedFiles) ? "✅ Available" : "❌ Missing",
			"The generated editor embeds the sample model and can load it without file selection.");
		row(out, "Domain instance XMI export",
			hasStandalone(generatedFiles) ? "✅ Available" : "❌ Missing",
			"The generated editor can export created models as EMF-style XMI using the domain namespace metadata.");
		row(out, "Generated validations",
			spec.getValidations().isEmpty() ? "⚠️ None" : "✅ " + spec.getValidations().size(),
			spec.getValidations().isEmpty()
				? "No cardinality, required, uniqueness or must-follow validations were generated."
				: "Validation rules are generated into the editor runtime.");
		row(out, "Advanced custom semantics",
			"⚠️ Manual extension",
			"Custom semantic behavior beyond declared references, containments, fields and validations is not inferred automatically.");
		row(out, "Smoke test",
			"▶ Optional",
			"Run `node scripts/smoke-test-generated.mjs` from the repository root to load samples automatically in a browser.");
		tableEnd(out);
	}

	private static boolean hasStandalone(Collection<String> generatedFiles) {
		for (String file : generatedFiles) {
			if (file != null && file.endsWith("_standalone.html")) return true;
		}
		return false;
	}

	private static boolean hasSampleModel(Collection<String> generatedFiles) {
		for (String file : generatedFiles) {
			if (file != null && file.endsWith("sample_model.json")) return true;
		}
		return false;
	}

	private static void appendEcoreNextSteps(StringBuilder out) {
		out.append("<section class=\"callout\">\n");
		out.append("<h2>Recommended Next Steps for an Ecore Developer</h2>\n");
		out.append("<ol>\n");
		out.append("<li>Open the generated <code>*_standalone.html</code> file and create a small model.</li>\n");
		out.append("<li>Check this report's EClass, EAttribute and EReference mappings.</li>\n");
		out.append("<li>If the structure is correct but the blocks are hard to read, add only presentation annotations such as <code>source=\"blockly\" message0</code>, <code>colour</code>, <code>category</code> or <code>tooltip</code>.</li>\n");
		out.append("<li>If labels in reference dropdowns are not meaningful, add <code>source=\"ui\" referenceLabelField=...</code>.</li>\n");
		out.append("<li>Rerun the same Eclipse launch configuration and compare the new report.</li>\n");
		out.append("</ol>\n");
		out.append("</section>\n");
	}

	private static void appendDslNextSteps(StringBuilder out) {
		out.append("<section class=\"callout\">\n");
		out.append("<h2>Recommended Next Steps for a DSL Developer</h2>\n");
		out.append("<ol>\n");
		out.append("<li>Open the generated <code>*_standalone.html</code> file and build a representative model.</li>\n");
		out.append("<li>Check that containment, references, value inputs, shadow blocks and validations behave as expected.</li>\n");
		out.append("<li>Use <code>label</code>, <code>colour</code>, <code>widget</code>, <code>referenceLabelField</code>, <code>shadow</code> and <code>code</code> declarations to improve the editor.</li>\n");
		out.append("<li>Export domain instance XMI, JSON or code to verify that the blocks represent a processable model.</li>\n");
		out.append("</ol>\n");
		out.append("</section>\n");
	}

	private static void appendEcoreMapping(StringBuilder out, EPackage pkg, EditorSpec spec) {
		out.append("<h2>Metamodel to Blockly Mapping</h2>\n");
		Map<String, BlockTypeSpec> blockMap = blockMap(spec);
		tableStart(out, "EClass", "Generated block", "Role", "Fields / references");
		for (EClass eClass : allEClasses(pkg)) {
			BlockTypeSpec bt = blockMap.get(eClass.getName());
			if (bt == null) {
				row(out, eClass.getName(), "❌ Not generated", "❌ Skipped", "-");
			} else {
				row(out, eClass.getName(), "✅ " + bt.getTypeName(), role(bt),
					"✅ " + bt.getFields().size() + " fields, "
						+ bt.getStatementInputs().size() + " containments, "
						+ bt.getReferenceFields().size() + " references");
			}
		}
		tableEnd(out);
	}

	private static void appendEcoreCoverageMatrix(StringBuilder out) {
		out.append("<h2>Ecore Coverage Matrix</h2>\n");
		out.append("<p class=\"lead\">This matrix describes how the current generator treats common Ecore constructs. ");
		out.append("It separates automatic conversion, partial support and future extension points.</p>\n");
		tableStart(out, "Ecore construct", "Current Blockly conversion", "Status", "How to extend");
		row(out, "`EPackage.name/nsURI/nsPrefix`",
			"Editor domain name and XML/XMI namespace metadata",
			"✅ Implemented",
			"Already handled in `EcoreAdapter.fromEPackage`");
		row(out, "`EPackage.eSubpackages`",
			"Classifiers are collected recursively, but the generated editor uses one flat domain namespace",
			"⚠️ Partial",
			"Add package-scoped category prefixes or multi-domain output");
		row(out, "`EAnnotation source=\"blockly\"` on `EPackage`",
			"Workspace options such as `workspace.renderer`, `workspace.grid.*`, `workspace.zoom.*`, `workspace.toolboxType`",
			"✅ Implemented",
			"Add keys in `convertWorkspaceOptions` and `EditorSpec`");
		row(out, "`EAnnotation source=\"code\"` / `source=\"runtime\"` on `EPackage`",
			"Code export metadata and optional runtime kind",
			"✅ Implemented",
			"Extend package annotation readers and the HTML generator");
		row(out, "`EClass.name`",
			"Concrete class becomes a Blockly block type",
			"✅ Implemented",
			"Already handled in `convertEClass`");
		row(out, "`EClass.abstract` / `interface`",
			"Not shown as a toolbox block; used as abstract type/category information",
			"✅ Implemented",
			"Already filtered through `getConcreteBlockTypes`");
		row(out, "`EClass.eSuperTypes`",
			"Used for typed connections and subtype-compatible references; generic and multiple-inheritance details are simplified",
			"⚠️ Partial",
			"Store full supertype closure in the intermediate model");
		row(out, "`EClass.eOperations`",
			"Not translated into Blockly behavior or action blocks",
			"❌ Not implemented",
			"Design an operation-to-block/runtime mapping before adding code");
		row(out, "`EAttribute` with primitive `EDataType`",
			"Mapped to text, number or checkbox fields",
			"✅ Implemented",
			"Extend `convertEAttribute` for more data type mappings");
		row(out, "Custom `EDataType`",
			"Falls back to text input",
			"⚠️ Partial",
			"Use `instanceClassName` or annotation keys to select a Blockly field");
		row(out, "`EAttribute : EEnum` and `EEnumLiteral`",
			"Generated as a dropdown field",
			"✅ Implemented",
			"Already uses literal labels and values");
		row(out, "`EAttribute.iD` / `EClass.eIDAttribute`",
			"Generated as a normal field, used as `_modelId`, used as the default reference label and checked for uniqueness",
			"✅ Implemented",
			"Extend exported XML/XMI if external ID-based references are needed");
		row(out, "`EStructuralFeature.defaultValueLiteral`",
			"Used as the Blockly field default value",
			"✅ Implemented",
			"Already handled in `convertEAttribute`");
		row(out, "`ETypedElement.lowerBound/upperBound`",
			"Generates required and cardinality warnings",
			"✅ Implemented",
			"Add stricter Blockly connection checks if warnings are not enough");
		row(out, "Multi-valued `EAttribute`",
			"Rendered as a dedicated multi-value field with cardinality and uniqueness warnings",
			"✅ Implemented",
			"Add typed item editors if a domain needs richer list editing");
		row(out, "`EStructuralFeature.derived/transient/volatile/changeable=false`",
			"Skipped from editable Blockly fields",
			"✅ Deliberate skip",
			"Add read-only inspector support if derived values must be shown");
		row(out, "`EStructuralFeature.unsettable`",
			"Unset/set state is not represented",
			"❌ Not implemented",
			"Add tri-state field metadata and export support");
		row(out, "`ETypedElement.ordered/unique`",
			"Order is naturally preserved for statement stacks and list values; uniqueness warnings are generated for multi-valued fields/references",
			"⚠️ Partial",
			"Add hard constraints if warnings are not strict enough");
		row(out, "Containment `EReference`",
			"Generated as `input_statement` with child type checks",
			"✅ Implemented",
			"Use `source=\"blockly\" check=...` to override accepted child type");
		row(out, "Non-containment `EReference`",
			"Generated as dynamic reference dropdown or multiselect",
			"✅ Implemented",
			"Use `source=\"ui\" referenceLabelField=...` to improve labels");
		row(out, "`EReference` annotated as `type=input_value`",
			"Generated as Blockly `input_value`, optionally with `check` and `shadow`",
			"✅ Implemented",
			"Already handled in `convertEClass`");
		row(out, "`EReference.eOpposite` / `container`",
			"Opposite non-containment references are recorded and synchronized in the generated reference-field runtime; containment/container opposites are still simplified",
			"⚠️ Partial",
			"Extend the synchronizer if container references must be exposed as editable fields");
		row(out, "`EReference.resolveProxies` / `eKeys`",
			"Not represented in the Blockly editor",
			"❌ Not implemented",
			"Define reference identity and proxy-loading semantics for browser runtime");
		row(out, "`EGenericType` / `ETypeParameter`",
			"Only the erased `eType` is effectively used",
			"⚠️ Partial",
			"Represent generic bindings in `EditorSpec`");
		row(out, "`EValidator`, OCL and validation delegates",
			"`source=\"validation\"` expressions are generated as runtime checks; a small OCL invariant subset can be translated",
			"⚠️ Partial",
			"Extend the OCL translator or plug in a dedicated validation engine for full OCL/EValidator coverage");
		tableEnd(out);
	}

	private static void appendEcoreRecommendations(StringBuilder out, EPackage pkg) {
		out.append("<h2>Recommended Improvements</h2>\n");
		out.append("<p class=\"lead\">These recommendations are generated from the Ecore model. They are not errors; they indicate where a metamodel developer may want to add optional annotations or custom extensions.</p>\n");
		tableStart(out, "Priority", "Finding", "Recommended action");
		boolean any = false;
		for (EClass eClass : allEClasses(pkg)) {
			if (!eClass.isAbstract() && !eClass.isInterface() && eClass.getEAnnotation("blockly") == null) {
				row(out, "P1", "Class `" + eClass.getName() + "` has no Blockly presentation annotation",
					"Add `source=\"blockly\" message0`, `colour`, `category` or `tooltip` if the default block is not readable enough.");
				any = true;
			}
			for (EReference ref : eClass.getEAllReferences()) {
				if (!ref.isContainment() && ref.getEAnnotation("ui") == null && ref.getEReferenceType() != null) {
					row(out, "P1", "Reference `" + eClass.getName() + "." + ref.getName() + "` uses default labels",
						"Add `source=\"ui\" referenceLabelField=<attribute>` on the EReference or define an ID/name attribute in target `" + ref.getEReferenceType().getName() + "`.");
					any = true;
				}
			}
		}
		if (validationConstraintCount(pkg) > 0) {
			row(out, "P2", "Validation annotations or OCL constraints detected",
				"Simple expressions are generated. For full OCL or Java `EValidator`, keep them as an explicit validation-extension task.");
			any = true;
		}
		if (operationCount(pkg) > 0) {
			row(out, "P2", "EOperations detected",
				"Decide whether each operation should become an action block, a code-generation template or remain outside the visual editor.");
			any = true;
		}
		if (!any) {
			row(out, "-", "No immediate recommendations", "The generated editor can be reviewed directly in the standalone HTML file.");
		}
		tableEnd(out);
	}

	private static void appendDslMapping(StringBuilder out, DomainModel domain, EditorSpec spec) {
		out.append("<h2>DSL to Blockly Mapping</h2>\n");
		Map<String, BlockTypeSpec> blockMap = blockMap(spec);
		tableStart(out, "DSL class", "Generated block", "Role", "Features");
		for (ClassDef cls : domain.getClasses()) {
			BlockTypeSpec bt = blockMap.get(cls.getName());
			row(out, cls.getName(), bt != null ? "✅ " + bt.getTypeName() : "❌ Not generated",
				bt != null ? role(bt) : "❌ Skipped", featureSummary(cls, bt));
		}
		tableEnd(out);
	}

	private static void appendValidationSummary(StringBuilder out, EditorSpec spec) {
		out.append("<h2>Validation Summary</h2>\n");
		Map<ValidationType, Integer> counts = new LinkedHashMap<>();
		for (ValidationSpec validation : spec.getValidations()) {
			counts.put(validation.getType(), counts.getOrDefault(validation.getType(), 0) + 1);
		}
		tableStart(out, "Validation type", "Count", "Meaning");
		for (ValidationType type : ValidationType.values()) {
			int count = counts.getOrDefault(type, 0);
			if (count > 0) row(out, type.name(), "✅ " + count, validationMeaning(type));
		}
		if (counts.isEmpty()) row(out, "-", "⚠️ 0", "No generated validation rules");
		tableEnd(out);
	}

	private static void appendVisualValidationBlocks(StringBuilder out, EditorSpec spec) {
		out.append("<h2>Visual Validation Blocks</h2>\n");
		out.append("<p class=\"lead\">These rules are also serialized in <code>validation_blocks.json</code> with Blockly JSON block definitions and Blockly-like block trees. ");
		out.append("The model prefers high-level custom validation blocks and preserves lower-level Blockly expressions when useful.</p>\n");
		tableStart(out, "Rule", "Target", "Validation", "Visual block root");
		boolean any = false;
		for (ValidationSpec validation : spec.getValidations()) {
			if (validation.getVisualBlock() == null && validation.getVisualExpression() == null) continue;
			any = true;
			row(out,
				value(validation.getName()),
				value(validation.getOwnerType() != null ? validation.getOwnerType() : validation.getTargetType()),
				validation.getType() != null ? validation.getType().name() : "-",
				visualValidationLabel(validation));
		}
		if (!any) {
			row(out, "-", "-", "⚠️ none", "No visual validation block generated yet.");
		}
		tableEnd(out);
		if (any) appendVisualValidationPreview(out, spec);
	}

	private static void appendVisualValidationPreview(StringBuilder out, EditorSpec spec) {
		out.append("<div class=\"validation-preview-list\">\n");
		int index = 0;
		for (ValidationSpec validation : spec.getValidations()) {
			if (validation.getVisualBlock() == null && validation.getVisualExpression() == null) continue;
			out.append("<details class=\"validation-preview\"");
			if (index == 0) out.append(" open");
			out.append(">\n");
			out.append("<summary>")
				.append(escape(value(validation.getName())))
				.append(" -> ")
				.append(escape(value(validation.getType() != null ? validation.getType().name() : "validation")))
				.append("</summary>\n");
			out.append("<div class=\"validation-tree\">\n");
			appendValidationRuleNode(out, validation);
			out.append("</div>\n</details>\n");
			index++;
		}
		out.append("</div>\n");
	}

	private static void appendValidationRuleNode(StringBuilder out, ValidationSpec validation) {
		appendNode(out,
			"validation_rule",
			"name=" + value(validation.getName())
				+ ", target=" + value(validation.getOwnerType() != null ? validation.getOwnerType() : validation.getTargetType())
				+ ", type=" + value(validation.getType() != null ? validation.getType().name() : "-"));
		out.append("<div class=\"validation-children\">\n");
		out.append("<div class=\"validation-edge\">CONDITION</div>\n");
		if (validation.getVisualBlock() != null) {
			appendValidationBlockPreview(out, validation.getVisualBlock());
		} else {
			appendExpressionPreview(out, validation.getVisualExpression());
		}
		out.append("</div>\n");
	}

	private static void appendValidationBlockPreview(StringBuilder out, ValidationBlockSpec block) {
		if (block == null) {
			appendNode(out, "null", "No visual block");
			return;
		}
		appendNode(out, value(block.getBlocklyBlockType()), visualBlockMeta(block));
		Map<String, ValidationExpressionSpec> inputs = BlocklySpecModelQueries.inputs(block);
		if (inputs.isEmpty()) return;
		out.append("<div class=\"validation-children\">\n");
		for (Map.Entry<String, ValidationExpressionSpec> entry : inputs.entrySet()) {
			out.append("<div class=\"validation-edge\">").append(escape(entry.getKey())).append("</div>\n");
			appendExpressionPreview(out, entry.getValue());
		}
		out.append("</div>\n");
	}

	private static void appendExpressionPreview(StringBuilder out, ValidationExpressionSpec expression) {
		if (expression == null) {
			appendNode(out, "null", "No visual expression");
			return;
		}
		appendNode(out, visualBlockType(expression), visualBlockMeta(expression));
		if (expression.getChildren().isEmpty()) return;
		out.append("<div class=\"validation-children\">\n");
		for (int i = 0; i < expression.getChildren().size(); i++) {
			out.append("<div class=\"validation-edge\">").append(i == 0 ? "A" : i == 1 ? "B" : "INPUT " + (i + 1)).append("</div>\n");
			appendExpressionPreview(out, expression.getChildren().get(i));
		}
		out.append("</div>\n");
	}

	private static String visualValidationLabel(ValidationSpec validation) {
		if (validation.getVisualBlock() != null) {
			return "`" + value(validation.getVisualBlock().getBlocklyBlockType()) + "`";
		}
		return visualExpressionLabel(validation.getVisualExpression());
	}

	private static String visualBlockMeta(ValidationBlockSpec block) {
		Map<String, String> fields = BlocklySpecModelQueries.fields(block);
		if (fields.isEmpty()) return "";
		StringBuilder meta = new StringBuilder();
		for (Map.Entry<String, String> entry : fields.entrySet()) {
			if (meta.length() > 0) meta.append(", ");
			meta.append(entry.getKey()).append("=").append(value(entry.getValue()));
		}
		return meta.toString();
	}

	private static void appendNode(StringBuilder out, String blockType, String meta) {
		out.append("<div class=\"validation-node\"><code>")
			.append(escape(value(blockType)))
			.append("</code>");
		if (meta != null && !meta.isBlank()) {
			out.append("<div class=\"validation-node-meta\">")
				.append(escape(meta))
				.append("</div>");
		}
		out.append("</div>\n");
	}

	private static void appendEcoreCustomizationHints(StringBuilder out, EPackage pkg) {
		out.append("<h2>Customization Hints</h2>\n");
		out.append("<p class=\"lead\">Use this section when the generated editor works but you want a more specific Blockly presentation. ");
		out.append("Structural information should stay in Ecore; add only the annotation keys needed for the desired UI effect.</p>\n");
		tableStart(out, "Desired result", "Where to add it", "Annotation keys");

		for (EClass eClass : allEClasses(pkg)) {
			row(out, "Change block text", eClass.getName(),
				"`source=\"blockly\"`: `message0=\"" + eClass.getName() + " %1 ...\"`");
			row(out, "Change colour / category / tooltip", eClass.getName(),
				"`source=\"blockly\"`: `colour=210`, `category=App/Screens`, `tooltip=...`, `helpUrl=...`");
			if (!eClass.isAbstract() && !eClass.isInterface()) {
				row(out, "Show fields in one line", eClass.getName(),
					"`source=\"blockly\"`: `inputsInline=true`");
			}
			if (eClass.getESuperTypes().isEmpty()) {
				row(out, "Make this block an output/value block", eClass.getName(),
					"`source=\"blockly\"`: `output=true` or `output=TypeName`");
			}

			for (EAttribute attr : eClass.getEAllAttributes()) {
				if (attr.getEAttributeType() instanceof EEnum) continue;
				String typeName = typeName(attr.getEAttributeType());
				if (isNumericType(typeName)) {
					row(out, "Limit number range", eClass.getName() + "." + attr.getName(),
						"`source=\"blockly\"`: `min=1`, `max=100`");
				}
				if ("EString".equals(typeName) || "EChar".equals(typeName)) {
					row(out, "Use a specialised Blockly field", eClass.getName() + "." + attr.getName(),
						"`source=\"blockly\"`: `type=field_colour`, `type=field_image`, or `type=field_label`");
					row(out, "Configure image field", eClass.getName() + "." + attr.getName(),
						"`source=\"blockly\"`: `type=field_image`, `src=...`, `width=40`, `height=40`, `alt=...`");
				}
			}

			for (EReference ref : eClass.getEAllReferences()) {
				if (!ref.isContainment()) {
					row(out, "Use a value input instead of a dropdown", eClass.getName() + "." + ref.getName(),
						"`source=\"blockly\"`: `type=input_value`, optional `check=" + typeName(ref.getEReferenceType()) + "`, `shadow=BlockType`");
				} else {
					row(out, "Override accepted child type", eClass.getName() + "." + ref.getName(),
						"`source=\"blockly\"`: `check=" + typeName(ref.getEReferenceType()) + "`");
				}
			}
		}

		row(out, "Add ordering validation", "EClass",
			"`source=\"validation\"`: `mustFollow=OtherBlockType`");
		row(out, "Improve generated field presentation", "EAttribute / EReference",
			"`source=\"ui\"`: `widget=slider`, `label=...`, `help=...`, `group=...`, `order=1`, `referenceLabelField=name`");
		tableEnd(out);
	}

	private static void appendEcoreAttention(StringBuilder out, EPackage pkg) {
		out.append("<h2>What To Check</h2>\n");
		tableStart(out, "Topic", "Status");
		List<String> skipped = skippedFeatures(pkg);
		row(out, "Skipped structural features", skipped.isEmpty()
			? "✅ None detected"
			: "⚠️ " + String.join(", ", skipped));
		row(out, "OCL / validation constraints", validationConstraintCount(pkg) == 0
			? "✅ No OCL or validation annotations detected"
			: "⚠️ " + validationConstraintCount(pkg) + " constraint annotation(s) detected; supported expressions are generated, complex OCL remains an extension point");
		row(out, "EOperations", operationCount(pkg) == 0
			? "✅ No EOperations detected"
			: "❌ " + operationCount(pkg) + " EOperations not translated into Blockly behavior");
		row(out, "EOpposite", oppositeCount(pkg) == 0
			? "✅ No opposite references detected"
			: "✅ " + oppositeCount(pkg) + " opposite reference declaration(s) used for generated synchronization");
		tableEnd(out);
	}

	private static void appendDslAttention(StringBuilder out, DomainModel domain) {
		out.append("<h2>What To Check</h2>\n");
		tableStart(out, "Topic", "Status");
		row(out, "Required fields", "✅ Generated from the DSL `required` keyword");
		row(out, "Containment cardinality", "✅ Generated from `contains [lower..upper]`");
		row(out, "Must-follow constraints", "✅ Generated from `constraint ... must follow ...`");
		row(out, "Opposite references", dslOppositeCount(domain) == 0
			? "✅ No opposite references declared"
			: "✅ " + dslOppositeCount(domain) + " opposite references declared and synchronized in the generated runtime");
		row(out, "Advanced semantics", "❌ Custom semantic constraints are not generated automatically");
		tableEnd(out);
	}

	private static void tableStart(StringBuilder out, String... headers) {
		out.append("<div class=\"table-wrap\"><table><thead><tr>");
		for (String header : headers) out.append("<th>").append(escape(header)).append("</th>");
		out.append("</tr></thead><tbody>\n");
	}

	private static void row(StringBuilder out, String... cells) {
		out.append("<tr>");
		for (String cell : cells) out.append("<td>").append(inline(value(cell))).append("</td>");
		out.append("</tr>\n");
	}

	private static void rowLinked(StringBuilder out, String file, String purpose) {
		out.append("<tr><td><a href=\"")
			.append(escapeAttr(file))
			.append("\">")
			.append(escape(file))
			.append("</a></td><td>")
			.append(inline(value(purpose)))
			.append("</td></tr>\n");
	}

	private static void rowPipelineLinked(StringBuilder out, String step, String file, String meaning) {
		out.append("<tr><td>")
			.append(inline(value(step)))
			.append("</td><td><a href=\"")
			.append(escapeAttr(file))
			.append("\">")
			.append(escape(file))
			.append("</a></td><td>")
			.append(inline(value(meaning)))
			.append("</td></tr>\n");
	}

	private static void tableEnd(StringBuilder out) {
		out.append("</tbody></table></div>\n");
	}

	private static Map<String, BlockTypeSpec> blockMap(EditorSpec spec) {
		Map<String, BlockTypeSpec> result = new LinkedHashMap<>();
		for (BlockTypeSpec bt : spec.getBlockTypes()) result.put(bt.getTypeName(), bt);
		return result;
	}

	private static List<EClass> allEClasses(EPackage pkg) {
		List<EClass> result = new ArrayList<>();
		collectEClasses(pkg, result);
		return result;
	}

	private static void collectEClasses(EPackage pkg, List<EClass> result) {
		for (EClassifier classifier : pkg.getEClassifiers()) {
			if (classifier instanceof EClass) result.add((EClass) classifier);
		}
		for (EPackage child : pkg.getESubpackages()) collectEClasses(child, result);
	}

	private static String role(BlockTypeSpec bt) {
		if (bt.isAbstract()) return "Abstract type";
		switch (bt.getConnectionType()) {
			case NONE: return "Root block";
			case OUTPUT:
			case OUTPUT_TYPED: return "Expression/output block";
			case TYPED: return "Typed statement block";
			default: return "Statement block";
		}
	}

	private static String featureSummary(ClassDef cls, BlockTypeSpec bt) {
		int attributes = 0, containments = 0, references = 0, values = 0;
		for (Feature feature : cls.getFeatures()) {
			String name = feature.eClass().getName();
			if ("Attribute".equals(name)) attributes++;
			else if ("Containment".equals(name)) containments++;
			else if ("Reference".equals(name)) references++;
			else if ("ValueInput".equals(name)) values++;
		}
		if (bt == null) return "-";
		return attributes + " attributes, " + containments + " containments, "
			+ references + " references, " + values + " value inputs";
	}

	private static String validationMeaning(ValidationType type) {
		switch (type) {
			case MUST_FOLLOW: return "Ordering relation between block types";
			case CARDINALITY: return "Number of nested blocks in a statement input";
			case REQUIRED: return "Mandatory field or reference value";
			case FIELD_CARDINALITY: return "Bounds for multi-valued fields or references";
			case UNIQUE: return "Duplicate values in ID fields or multi-valued fields/references";
			case EXPRESSION: return "Semantic expression checks from validation/OCL annotations";
			default: return "-";
		}
	}

	private static String visualExpressionLabel(ValidationExpressionSpec expression) {
		if (expression == null || expression.getKind() == null) return "-";
		switch (expression.getKind()) {
			case LOGIC_OPERATION:
				return "`logic_operation` " + value(expression.getOperator()) + " with " + expression.getChildren().size() + " child block(s)";
			case LOGIC_NEGATE:
				return "`logic_negate`";
			case LOGIC_COMPARE:
				return "`logic_compare` " + value(expression.getOperator());
			case NUMBER_LITERAL:
				return "`math_number` " + value(expression.getLiteral());
			case STRING_LITERAL:
				return "`text`";
			case BOOLEAN_LITERAL:
				return "`logic_boolean` " + value(expression.getLiteral());
			case FIELD_VALUE:
				return "`validation_field_value` " + value(expression.getFieldName());
			case FIELD_NUMBER:
				return "`validation_field_number` " + value(expression.getFieldName());
			case FIELD_EXISTS:
				return "`validation_field_exists` " + value(expression.getFieldName());
			case FIELD_COUNT:
				return "`validation_field_count` " + value(expression.getFieldName());
			case FIELD_UNIQUE:
				return "`validation_field_unique` " + value(expression.getFieldName());
			case TYPE_FIELD_UNIQUE:
				return "`validation_type_field_unique` " + value(expression.getTypeName()) + "." + value(expression.getFieldName());
			case INPUT_COUNT:
				return "`validation_input_count` " + value(expression.getFieldName());
			case PREVIOUS_BLOCK_IS:
				return "`validation_previous_block_is` " + value(expression.getTypeName());
			case CUSTOM:
			default:
				return "`" + value(expression.getBlocklyBlockType()) + "`";
		}
	}

	private static String visualBlockType(ValidationExpressionSpec expression) {
		if (expression == null || expression.getKind() == null) return "-";
		switch (expression.getKind()) {
			case LOGIC_OPERATION: return "logic_operation";
			case LOGIC_NEGATE: return "logic_negate";
			case LOGIC_COMPARE: return "logic_compare";
			case NUMBER_LITERAL: return "math_number";
			case STRING_LITERAL: return "text";
			case BOOLEAN_LITERAL: return "logic_boolean";
			case FIELD_VALUE: return "validation_field_value";
			case FIELD_NUMBER: return "validation_field_number";
			case FIELD_EXISTS: return "validation_field_exists";
			case FIELD_COUNT: return "validation_field_count";
			case FIELD_UNIQUE: return "validation_field_unique";
			case TYPE_FIELD_UNIQUE: return "validation_type_field_unique";
			case INPUT_COUNT: return "validation_input_count";
			case PREVIOUS_BLOCK_IS: return "validation_previous_block_is";
			case CUSTOM:
			default:
				return value(expression.getBlocklyBlockType());
		}
	}

	private static String visualBlockMeta(ValidationExpressionSpec expression) {
		if (expression == null || expression.getKind() == null) return "";
		switch (expression.getKind()) {
			case LOGIC_OPERATION:
			case LOGIC_COMPARE:
				return "OP=" + value(expression.getOperator());
			case NUMBER_LITERAL:
				return "NUM=" + value(expression.getLiteral());
			case STRING_LITERAL:
				return "TEXT=" + value(expression.getLiteral());
			case BOOLEAN_LITERAL:
				return "BOOL=" + value(expression.getLiteral());
			case FIELD_VALUE:
			case FIELD_NUMBER:
			case FIELD_EXISTS:
			case FIELD_COUNT:
			case FIELD_UNIQUE:
				return "FIELD=" + value(expression.getFieldName());
			case TYPE_FIELD_UNIQUE:
				return "TYPE=" + value(expression.getTypeName()) + ", FIELD=" + value(expression.getFieldName());
			case INPUT_COUNT:
				return "INPUT=" + value(expression.getFieldName());
			case PREVIOUS_BLOCK_IS:
				return "TYPE=" + value(expression.getTypeName());
			case LOGIC_NEGATE:
				return "";
			case CUSTOM:
			default:
				return value(expression.getLiteral());
		}
	}

	private static boolean isNumericType(String typeName) {
		if (typeName == null) return false;
		switch (typeName) {
			case "EInt":
			case "ELong":
			case "EShort":
			case "EBigInteger":
			case "EFloat":
			case "EDouble":
			case "EBigDecimal":
				return true;
			default:
				return false;
		}
	}

	private static String typeName(EClassifier type) {
		return type == null ? "" : type.getName();
	}

	private static List<String> skippedFeatures(EPackage pkg) {
		List<String> skipped = new ArrayList<>();
		for (EClass eClass : allEClasses(pkg)) {
			for (EStructuralFeature feature : eClass.getEAllStructuralFeatures()) {
				if (feature.isDerived() || feature.isTransient() || feature.isVolatile() || !feature.isChangeable()) {
					skipped.add(eClass.getName() + "." + feature.getName());
				}
			}
		}
		return skipped;
	}

	private static int operationCount(EPackage pkg) {
		int count = 0;
		for (EClass eClass : allEClasses(pkg)) count += eClass.getEOperations().size();
		return count;
	}

	private static int unsupportedEcoreConstructCount(EPackage pkg) {
		return operationCount(pkg)
			+ unsettableFeatureCount(pkg)
			+ genericConstructCount(pkg)
			+ keyReferenceCount(pkg)
			+ validationConstraintCount(pkg);
	}

	private static int unsettableFeatureCount(EPackage pkg) {
		int count = 0;
		for (EClass eClass : allEClasses(pkg)) {
			for (EStructuralFeature feature : eClass.getEAllStructuralFeatures()) {
				if (feature.isUnsettable()) count++;
			}
		}
		return count;
	}

	private static int genericConstructCount(EPackage pkg) {
		int count = 0;
		for (EClass eClass : allEClasses(pkg)) {
			count += eClass.getETypeParameters().size();
			for (EGenericType genericSuper : eClass.getEGenericSuperTypes()) {
				if (isGenericDetail(genericSuper)) count++;
			}
			for (EStructuralFeature feature : eClass.getEAllStructuralFeatures()) {
				if (isGenericDetail(feature.getEGenericType())) count++;
			}
			for (EOperation operation : eClass.getEOperations()) {
				count += operation.getETypeParameters().size();
				if (isGenericDetail(operation.getEGenericType())) count++;
			}
		}
		return count;
	}

	private static boolean isGenericDetail(EGenericType genericType) {
		if (genericType == null) return false;
		return genericType.getETypeParameter() != null
			|| genericType.getELowerBound() != null
			|| genericType.getEUpperBound() != null
			|| !genericType.getETypeArguments().isEmpty();
	}

	private static int keyReferenceCount(EPackage pkg) {
		int count = 0;
		for (EClass eClass : allEClasses(pkg)) {
			for (EReference ref : eClass.getEAllReferences()) {
				if (!ref.getEKeys().isEmpty()) count++;
			}
		}
		return count;
	}

	private static int oppositeCount(EPackage pkg) {
		int count = 0;
		for (EClass eClass : allEClasses(pkg)) {
			for (EReference ref : eClass.getEAllReferences()) {
				if (ref.getEOpposite() != null) count++;
			}
		}
		return count;
	}

	private static int validationConstraintCount(EPackage pkg) {
		int count = 0;
		for (EClass eClass : allEClasses(pkg)) {
			EAnnotation validationAnn = eClass.getEAnnotation("validation");
			if (validationAnn != null) {
				for (String key : validationAnn.getDetails().keySet()) {
					if (key != null && (key.equals("expression") || key.equals("condition") || key.equals("js")
						|| key.equals("ocl") || key.startsWith("expression.") || key.startsWith("condition.")
						|| key.startsWith("js.") || key.startsWith("ocl."))) {
						count++;
					}
				}
			}
			EAnnotation ecoreAnn = eClass.getEAnnotation("http://www.eclipse.org/emf/2002/Ecore");
			if (ecoreAnn != null && ecoreAnn.getDetails().get("constraints") != null) {
				for (String name : ecoreAnn.getDetails().get("constraints").split("[,\\s]+")) {
					if (!name.isBlank()) count++;
				}
			}
		}
		return count;
	}

	private static int dslOppositeCount(DomainModel domain) {
		int count = 0;
		for (ClassDef cls : domain.getClasses()) {
			for (Feature feature : cls.getFeatures()) {
				if (feature instanceof Reference && ((Reference) feature).getOppositeName() != null) count++;
			}
		}
		return count;
	}

	private static String purpose(String file) {
		String fileName = file;
		int slash = file.lastIndexOf('/');
		if (slash >= 0) fileName = file.substring(slash + 1);
		if (isIntermediateXmi(file)) return "✅ Formal EditorSpec EMF/XMI intermediate model reloaded before HTML generation";
		if (file.endsWith("_standalone.html")) return "✅ Open this file to use the generated editor";
		if (file.endsWith("_editor.html")) return "✅ Modular HTML editor";
		if (file.endsWith("_blocks.js")) return "✅ Blockly block definitions";
		if (file.endsWith("_validations.js")) return "✅ Validation logic";
		if (file.endsWith("validation_workspace.html")) return "✅ Editable Blockly validation workspace";
		if (file.endsWith("validation_blocks.json") || file.endsWith("validationBlocks.json")) return "✅ Visual validation block model";
		if (file.endsWith("validation_runtime.js") || file.endsWith("validationRuntime.js")) return "✅ Validation block expression runtime";
		if (fileName.equals("sample_model.json")) return "✅ Example model for the Load Sample button and JSON import";
		if (fileName.equals("README.md")) return "✅ Output-folder quick start";
		if (file.startsWith("html/")) return "✅ Classic HTML target artifact";
		return "Generated artifact";
	}

	public static String render(String markdown, String title) {
		StringBuilder out = new StringBuilder();
		out.append("<!doctype html>\n<html lang=\"en\">\n<head>\n");
		out.append("<meta charset=\"utf-8\">\n");
		out.append("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
		out.append("<title>").append(escape(title)).append("</title>\n");
		out.append("<style>\n");
		out.append("""
			:root {
			  color-scheme: light;
			  --bg: #f7f8fa;
			  --panel: #ffffff;
			  --text: #20242a;
			  --muted: #5c6673;
			  --border: #d7dce2;
			  --header: #eef2f6;
			  --accent: #245a9c;
			}
			* { box-sizing: border-box; }
			body {
			  margin: 0;
			  background: var(--bg);
			  color: var(--text);
			  font: 14px/1.55 -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
			}
			main {
			  max-width: 1180px;
			  margin: 0 auto;
			  padding: 32px 24px 56px;
			}
			h1 {
			  margin: 0 0 12px;
			  font-size: 28px;
			  line-height: 1.2;
			}
			h2 {
			  margin: 34px 0 12px;
			  padding-top: 18px;
			  border-top: 1px solid var(--border);
			  font-size: 20px;
			}
			p { max-width: 820px; color: var(--muted); }
			.table-wrap {
			  overflow-x: auto;
			  margin: 12px 0 22px;
			  border: 1px solid var(--border);
			  border-radius: 8px;
			  background: var(--panel);
			}
			table {
			  width: 100%;
			  border-collapse: collapse;
			  min-width: 720px;
			}
			th, td {
			  padding: 9px 12px;
			  border-bottom: 1px solid var(--border);
			  border-right: 1px solid var(--border);
			  vertical-align: top;
			  text-align: left;
			}
			th:last-child, td:last-child { border-right: 0; }
			tr:last-child td { border-bottom: 0; }
			th {
			  position: sticky;
			  top: 0;
			  background: var(--header);
			  font-weight: 650;
			}
			code {
			  padding: 1px 5px;
			  border-radius: 4px;
			  background: #eef1f4;
			  color: #173b63;
			  font-family: ui-monospace, SFMono-Regular, Menlo, Consolas, monospace;
			  font-size: 0.92em;
			}
			""");
		out.append("</style>\n</head>\n<body>\n<main>\n");

		List<String> lines = List.of(markdown.split("\\R", -1));
		for (int i = 0; i < lines.size(); i++) {
			String line = lines.get(i);
			if (line.isBlank()) continue;
			if (line.startsWith("# ")) {
				out.append("<h1>").append(inline(line.substring(2).trim())).append("</h1>\n");
			} else if (line.startsWith("## ")) {
				out.append("<h2>").append(inline(line.substring(3).trim())).append("</h2>\n");
			} else if (isTableStart(lines, i)) {
				List<String> tableLines = new ArrayList<>();
				while (i < lines.size() && lines.get(i).startsWith("|")) {
					tableLines.add(lines.get(i));
					i++;
				}
				i--;
				appendTable(out, tableLines);
			} else {
				out.append("<p>").append(inline(line.trim())).append("</p>\n");
			}
		}

		out.append("</main>\n</body>\n</html>\n");
		return out.toString();
	}

	private static boolean isTableStart(List<String> lines, int index) {
		if (index + 1 >= lines.size()) return false;
		return lines.get(index).startsWith("|") && lines.get(index + 1).matches("\\|[\\s:\\-\\|]+");
	}

	private static void appendTable(StringBuilder out, List<String> tableLines) {
		if (tableLines.size() < 2) return;
		out.append("<div class=\"table-wrap\"><table>\n<thead><tr>");
		for (String cell : cells(tableLines.get(0))) {
			out.append("<th>").append(inline(cell)).append("</th>");
		}
		out.append("</tr></thead>\n<tbody>\n");
		for (int i = 2; i < tableLines.size(); i++) {
			out.append("<tr>");
			for (String cell : cells(tableLines.get(i))) {
				out.append("<td>").append(inline(cell)).append("</td>");
			}
			out.append("</tr>\n");
		}
		out.append("</tbody></table></div>\n");
	}

	private static List<String> cells(String line) {
		String text = line.trim();
		if (text.startsWith("|")) text = text.substring(1);
		if (text.endsWith("|")) text = text.substring(0, text.length() - 1);
		String[] raw = text.split("(?<!\\\\)\\|", -1);
		List<String> cells = new ArrayList<>();
		for (String cell : raw) {
			cells.add(cell.replace("\\|", "|").trim());
		}
		return cells;
	}

	private static String inline(String text) {
		String escaped = escape(text).replace("&lt;br&gt;", "<br>");
		StringBuilder out = new StringBuilder();
		boolean code = false;
		for (int i = 0; i < escaped.length(); i++) {
			char ch = escaped.charAt(i);
			if (ch == '`') {
				out.append(code ? "</code>" : "<code>");
				code = !code;
			} else {
				out.append(ch);
			}
		}
		if (code) out.append("</code>");
		return out.toString();
	}

	private static String escape(String value) {
		if (value == null) return "";
		return value.replace("&", "&amp;")
			.replace("<", "&lt;")
			.replace(">", "&gt;")
			.replace("\"", "&quot;");
	}

	private static String escapeAttr(String value) {
		return escape(value).replace(" ", "%20");
	}

	private static String value(String value) {
		return value == null || value.isBlank() ? "-" : value;
	}
}
