/*
 * generated by Xtext 2.39.0
 */
package io.github.plortinus.model2blockly.scoping;


/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
public class Model2BlocklyScopeProvider extends AbstractModel2BlocklyScopeProvider {

}
