/**
 * generated by Xtext 2.42.0
 */
package io.github.plortinus.model2blockly.model2Blockly;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Constraint Def</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link io.github.plortinus.model2blockly.model2Blockly.ConstraintDef#getName <em>Name</em>}</li>
 *   <li>{@link io.github.plortinus.model2blockly.model2Blockly.ConstraintDef#getTarget <em>Target</em>}</li>
 *   <li>{@link io.github.plortinus.model2blockly.model2Blockly.ConstraintDef#getPredecessor <em>Predecessor</em>}</li>
 * </ul>
 *
 * @see io.github.plortinus.model2blockly.model2Blockly.Model2BlocklyPackage#getConstraintDef()
 * @model
 * @generated
 */
public interface ConstraintDef extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see io.github.plortinus.model2blockly.model2Blockly.Model2BlocklyPackage#getConstraintDef_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link io.github.plortinus.model2blockly.model2Blockly.ConstraintDef#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Target</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Target</em>' reference.
   * @see #setTarget(ClassDef)
   * @see io.github.plortinus.model2blockly.model2Blockly.Model2BlocklyPackage#getConstraintDef_Target()
   * @model
   * @generated
   */
  ClassDef getTarget();

  /**
   * Sets the value of the '{@link io.github.plortinus.model2blockly.model2Blockly.ConstraintDef#getTarget <em>Target</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Target</em>' reference.
   * @see #getTarget()
   * @generated
   */
  void setTarget(ClassDef value);

  /**
   * Returns the value of the '<em><b>Predecessor</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Predecessor</em>' reference.
   * @see #setPredecessor(ClassDef)
   * @see io.github.plortinus.model2blockly.model2Blockly.Model2BlocklyPackage#getConstraintDef_Predecessor()
   * @model
   * @generated
   */
  ClassDef getPredecessor();

  /**
   * Sets the value of the '{@link io.github.plortinus.model2blockly.model2Blockly.ConstraintDef#getPredecessor <em>Predecessor</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Predecessor</em>' reference.
   * @see #getPredecessor()
   * @generated
   */
  void setPredecessor(ClassDef value);

} // ConstraintDef
