/**
 * generated by Xtext 2.42.0
 */
package io.github.plortinus.model2blockly.model2Blockly;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Domain Model</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link io.github.plortinus.model2blockly.model2Blockly.DomainModel#getName <em>Name</em>}</li>
 *   <li>{@link io.github.plortinus.model2blockly.model2Blockly.DomainModel#getCodeLanguage <em>Code Language</em>}</li>
 *   <li>{@link io.github.plortinus.model2blockly.model2Blockly.DomainModel#getCodeFileExtension <em>Code File Extension</em>}</li>
 *   <li>{@link io.github.plortinus.model2blockly.model2Blockly.DomainModel#getRuntimeKind <em>Runtime Kind</em>}</li>
 *   <li>{@link io.github.plortinus.model2blockly.model2Blockly.DomainModel#getWorkspace <em>Workspace</em>}</li>
 *   <li>{@link io.github.plortinus.model2blockly.model2Blockly.DomainModel#getCategories <em>Categories</em>}</li>
 *   <li>{@link io.github.plortinus.model2blockly.model2Blockly.DomainModel#getClasses <em>Classes</em>}</li>
 *   <li>{@link io.github.plortinus.model2blockly.model2Blockly.DomainModel#getConstraints <em>Constraints</em>}</li>
 *   <li>{@link io.github.plortinus.model2blockly.model2Blockly.DomainModel#getValidations <em>Validations</em>}</li>
 * </ul>
 *
 * @see io.github.plortinus.model2blockly.model2Blockly.Model2BlocklyPackage#getDomainModel()
 * @model
 * @generated
 */
public interface DomainModel extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see io.github.plortinus.model2blockly.model2Blockly.Model2BlocklyPackage#getDomainModel_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link io.github.plortinus.model2blockly.model2Blockly.DomainModel#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Code Language</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Code Language</em>' attribute.
   * @see #setCodeLanguage(String)
   * @see io.github.plortinus.model2blockly.model2Blockly.Model2BlocklyPackage#getDomainModel_CodeLanguage()
   * @model
   * @generated
   */
  String getCodeLanguage();

  /**
   * Sets the value of the '{@link io.github.plortinus.model2blockly.model2Blockly.DomainModel#getCodeLanguage <em>Code Language</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Code Language</em>' attribute.
   * @see #getCodeLanguage()
   * @generated
   */
  void setCodeLanguage(String value);

  /**
   * Returns the value of the '<em><b>Code File Extension</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Code File Extension</em>' attribute.
   * @see #setCodeFileExtension(String)
   * @see io.github.plortinus.model2blockly.model2Blockly.Model2BlocklyPackage#getDomainModel_CodeFileExtension()
   * @model
   * @generated
   */
  String getCodeFileExtension();

  /**
   * Sets the value of the '{@link io.github.plortinus.model2blockly.model2Blockly.DomainModel#getCodeFileExtension <em>Code File Extension</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Code File Extension</em>' attribute.
   * @see #getCodeFileExtension()
   * @generated
   */
  void setCodeFileExtension(String value);

  /**
   * Returns the value of the '<em><b>Runtime Kind</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Runtime Kind</em>' attribute.
   * @see #setRuntimeKind(String)
   * @see io.github.plortinus.model2blockly.model2Blockly.Model2BlocklyPackage#getDomainModel_RuntimeKind()
   * @model
   * @generated
   */
  String getRuntimeKind();

  /**
   * Sets the value of the '{@link io.github.plortinus.model2blockly.model2Blockly.DomainModel#getRuntimeKind <em>Runtime Kind</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Runtime Kind</em>' attribute.
   * @see #getRuntimeKind()
   * @generated
   */
  void setRuntimeKind(String value);

  /**
   * Returns the value of the '<em><b>Workspace</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Workspace</em>' containment reference.
   * @see #setWorkspace(WorkspaceConfig)
   * @see io.github.plortinus.model2blockly.model2Blockly.Model2BlocklyPackage#getDomainModel_Workspace()
   * @model containment="true"
   * @generated
   */
  WorkspaceConfig getWorkspace();

  /**
   * Sets the value of the '{@link io.github.plortinus.model2blockly.model2Blockly.DomainModel#getWorkspace <em>Workspace</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Workspace</em>' containment reference.
   * @see #getWorkspace()
   * @generated
   */
  void setWorkspace(WorkspaceConfig value);

  /**
   * Returns the value of the '<em><b>Categories</b></em>' containment reference list.
   * The list contents are of type {@link io.github.plortinus.model2blockly.model2Blockly.CategoryDef}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Categories</em>' containment reference list.
   * @see io.github.plortinus.model2blockly.model2Blockly.Model2BlocklyPackage#getDomainModel_Categories()
   * @model containment="true"
   * @generated
   */
  EList<CategoryDef> getCategories();

  /**
   * Returns the value of the '<em><b>Classes</b></em>' containment reference list.
   * The list contents are of type {@link io.github.plortinus.model2blockly.model2Blockly.ClassDef}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Classes</em>' containment reference list.
   * @see io.github.plortinus.model2blockly.model2Blockly.Model2BlocklyPackage#getDomainModel_Classes()
   * @model containment="true"
   * @generated
   */
  EList<ClassDef> getClasses();

  /**
   * Returns the value of the '<em><b>Constraints</b></em>' containment reference list.
   * The list contents are of type {@link io.github.plortinus.model2blockly.model2Blockly.ConstraintDef}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Constraints</em>' containment reference list.
   * @see io.github.plortinus.model2blockly.model2Blockly.Model2BlocklyPackage#getDomainModel_Constraints()
   * @model containment="true"
   * @generated
   */
  EList<ConstraintDef> getConstraints();

  /**
   * Returns the value of the '<em><b>Validations</b></em>' containment reference list.
   * The list contents are of type {@link io.github.plortinus.model2blockly.model2Blockly.ValidationDef}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Validations</em>' containment reference list.
   * @see io.github.plortinus.model2blockly.model2Blockly.Model2BlocklyPackage#getDomainModel_Validations()
   * @model containment="true"
   * @generated
   */
  EList<ValidationDef> getValidations();

} // DomainModel
