/**
 * generated by Xtext 2.42.0
 */
package io.github.plortinus.model2blockly.model2Blockly;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Ui Options</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link io.github.plortinus.model2blockly.model2Blockly.UiOptions#getWidget <em>Widget</em>}</li>
 *   <li>{@link io.github.plortinus.model2blockly.model2Blockly.UiOptions#getUiLabel <em>Ui Label</em>}</li>
 *   <li>{@link io.github.plortinus.model2blockly.model2Blockly.UiOptions#getHelp <em>Help</em>}</li>
 *   <li>{@link io.github.plortinus.model2blockly.model2Blockly.UiOptions#getPlaceholder <em>Placeholder</em>}</li>
 *   <li>{@link io.github.plortinus.model2blockly.model2Blockly.UiOptions#getGroup <em>Group</em>}</li>
 *   <li>{@link io.github.plortinus.model2blockly.model2Blockly.UiOptions#getOrder <em>Order</em>}</li>
 *   <li>{@link io.github.plortinus.model2blockly.model2Blockly.UiOptions#isUiReadonly <em>Ui Readonly</em>}</li>
 *   <li>{@link io.github.plortinus.model2blockly.model2Blockly.UiOptions#isUiHidden <em>Ui Hidden</em>}</li>
 *   <li>{@link io.github.plortinus.model2blockly.model2Blockly.UiOptions#getVariant <em>Variant</em>}</li>
 *   <li>{@link io.github.plortinus.model2blockly.model2Blockly.UiOptions#getReferenceLabelField <em>Reference Label Field</em>}</li>
 * </ul>
 *
 * @see io.github.plortinus.model2blockly.model2Blockly.Model2BlocklyPackage#getUiOptions()
 * @model
 * @generated
 */
public interface UiOptions extends EObject
{
  /**
   * Returns the value of the '<em><b>Widget</b></em>' attribute.
   * The literals are from the enumeration {@link io.github.plortinus.model2blockly.model2Blockly.UiWidget}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Widget</em>' attribute.
   * @see io.github.plortinus.model2blockly.model2Blockly.UiWidget
   * @see #setWidget(UiWidget)
   * @see io.github.plortinus.model2blockly.model2Blockly.Model2BlocklyPackage#getUiOptions_Widget()
   * @model
   * @generated
   */
  UiWidget getWidget();

  /**
   * Sets the value of the '{@link io.github.plortinus.model2blockly.model2Blockly.UiOptions#getWidget <em>Widget</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Widget</em>' attribute.
   * @see io.github.plortinus.model2blockly.model2Blockly.UiWidget
   * @see #getWidget()
   * @generated
   */
  void setWidget(UiWidget value);

  /**
   * Returns the value of the '<em><b>Ui Label</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ui Label</em>' attribute.
   * @see #setUiLabel(String)
   * @see io.github.plortinus.model2blockly.model2Blockly.Model2BlocklyPackage#getUiOptions_UiLabel()
   * @model
   * @generated
   */
  String getUiLabel();

  /**
   * Sets the value of the '{@link io.github.plortinus.model2blockly.model2Blockly.UiOptions#getUiLabel <em>Ui Label</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ui Label</em>' attribute.
   * @see #getUiLabel()
   * @generated
   */
  void setUiLabel(String value);

  /**
   * Returns the value of the '<em><b>Help</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Help</em>' attribute.
   * @see #setHelp(String)
   * @see io.github.plortinus.model2blockly.model2Blockly.Model2BlocklyPackage#getUiOptions_Help()
   * @model
   * @generated
   */
  String getHelp();

  /**
   * Sets the value of the '{@link io.github.plortinus.model2blockly.model2Blockly.UiOptions#getHelp <em>Help</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Help</em>' attribute.
   * @see #getHelp()
   * @generated
   */
  void setHelp(String value);

  /**
   * Returns the value of the '<em><b>Placeholder</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Placeholder</em>' attribute.
   * @see #setPlaceholder(String)
   * @see io.github.plortinus.model2blockly.model2Blockly.Model2BlocklyPackage#getUiOptions_Placeholder()
   * @model
   * @generated
   */
  String getPlaceholder();

  /**
   * Sets the value of the '{@link io.github.plortinus.model2blockly.model2Blockly.UiOptions#getPlaceholder <em>Placeholder</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Placeholder</em>' attribute.
   * @see #getPlaceholder()
   * @generated
   */
  void setPlaceholder(String value);

  /**
   * Returns the value of the '<em><b>Group</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Group</em>' attribute.
   * @see #setGroup(String)
   * @see io.github.plortinus.model2blockly.model2Blockly.Model2BlocklyPackage#getUiOptions_Group()
   * @model
   * @generated
   */
  String getGroup();

  /**
   * Sets the value of the '{@link io.github.plortinus.model2blockly.model2Blockly.UiOptions#getGroup <em>Group</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Group</em>' attribute.
   * @see #getGroup()
   * @generated
   */
  void setGroup(String value);

  /**
   * Returns the value of the '<em><b>Order</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Order</em>' attribute.
   * @see #setOrder(int)
   * @see io.github.plortinus.model2blockly.model2Blockly.Model2BlocklyPackage#getUiOptions_Order()
   * @model
   * @generated
   */
  int getOrder();

  /**
   * Sets the value of the '{@link io.github.plortinus.model2blockly.model2Blockly.UiOptions#getOrder <em>Order</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Order</em>' attribute.
   * @see #getOrder()
   * @generated
   */
  void setOrder(int value);

  /**
   * Returns the value of the '<em><b>Ui Readonly</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ui Readonly</em>' attribute.
   * @see #setUiReadonly(boolean)
   * @see io.github.plortinus.model2blockly.model2Blockly.Model2BlocklyPackage#getUiOptions_UiReadonly()
   * @model
   * @generated
   */
  boolean isUiReadonly();

  /**
   * Sets the value of the '{@link io.github.plortinus.model2blockly.model2Blockly.UiOptions#isUiReadonly <em>Ui Readonly</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ui Readonly</em>' attribute.
   * @see #isUiReadonly()
   * @generated
   */
  void setUiReadonly(boolean value);

  /**
   * Returns the value of the '<em><b>Ui Hidden</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ui Hidden</em>' attribute.
   * @see #setUiHidden(boolean)
   * @see io.github.plortinus.model2blockly.model2Blockly.Model2BlocklyPackage#getUiOptions_UiHidden()
   * @model
   * @generated
   */
  boolean isUiHidden();

  /**
   * Sets the value of the '{@link io.github.plortinus.model2blockly.model2Blockly.UiOptions#isUiHidden <em>Ui Hidden</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ui Hidden</em>' attribute.
   * @see #isUiHidden()
   * @generated
   */
  void setUiHidden(boolean value);

  /**
   * Returns the value of the '<em><b>Variant</b></em>' attribute.
   * The literals are from the enumeration {@link io.github.plortinus.model2blockly.model2Blockly.UiVariant}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Variant</em>' attribute.
   * @see io.github.plortinus.model2blockly.model2Blockly.UiVariant
   * @see #setVariant(UiVariant)
   * @see io.github.plortinus.model2blockly.model2Blockly.Model2BlocklyPackage#getUiOptions_Variant()
   * @model
   * @generated
   */
  UiVariant getVariant();

  /**
   * Sets the value of the '{@link io.github.plortinus.model2blockly.model2Blockly.UiOptions#getVariant <em>Variant</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Variant</em>' attribute.
   * @see io.github.plortinus.model2blockly.model2Blockly.UiVariant
   * @see #getVariant()
   * @generated
   */
  void setVariant(UiVariant value);

  /**
   * Returns the value of the '<em><b>Reference Label Field</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Reference Label Field</em>' attribute.
   * @see #setReferenceLabelField(String)
   * @see io.github.plortinus.model2blockly.model2Blockly.Model2BlocklyPackage#getUiOptions_ReferenceLabelField()
   * @model
   * @generated
   */
  String getReferenceLabelField();

  /**
   * Sets the value of the '{@link io.github.plortinus.model2blockly.model2Blockly.UiOptions#getReferenceLabelField <em>Reference Label Field</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Reference Label Field</em>' attribute.
   * @see #getReferenceLabelField()
   * @generated
   */
  void setReferenceLabelField(String value);

} // UiOptions
