/**
 * generated by Xtext 2.42.0
 */
package io.github.plortinus.model2blockly.model2Blockly;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Value Input</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link io.github.plortinus.model2blockly.model2Blockly.ValueInput#getType <em>Type</em>}</li>
 *   <li>{@link io.github.plortinus.model2blockly.model2Blockly.ValueInput#getShadowType <em>Shadow Type</em>}</li>
 * </ul>
 *
 * @see io.github.plortinus.model2blockly.model2Blockly.Model2BlocklyPackage#getValueInput()
 * @model
 * @generated
 */
public interface ValueInput extends Feature
{
  /**
   * Returns the value of the '<em><b>Type</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' reference.
   * @see #setType(ClassDef)
   * @see io.github.plortinus.model2blockly.model2Blockly.Model2BlocklyPackage#getValueInput_Type()
   * @model
   * @generated
   */
  ClassDef getType();

  /**
   * Sets the value of the '{@link io.github.plortinus.model2blockly.model2Blockly.ValueInput#getType <em>Type</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' reference.
   * @see #getType()
   * @generated
   */
  void setType(ClassDef value);

  /**
   * Returns the value of the '<em><b>Shadow Type</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Shadow Type</em>' reference.
   * @see #setShadowType(ClassDef)
   * @see io.github.plortinus.model2blockly.model2Blockly.Model2BlocklyPackage#getValueInput_ShadowType()
   * @model
   * @generated
   */
  ClassDef getShadowType();

  /**
   * Sets the value of the '{@link io.github.plortinus.model2blockly.model2Blockly.ValueInput#getShadowType <em>Shadow Type</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Shadow Type</em>' reference.
   * @see #getShadowType()
   * @generated
   */
  void setShadowType(ClassDef value);

} // ValueInput
