<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore"
    name="typedfields"
    nsURI="https://plortinus.github.io/model2blockly/examples/typedfields"
    nsPrefix="typedfields">

  <eAnnotations source="blockly">
    <details key="workspace.renderer" value="zelos"/>
    <details key="workspace.trashcan" value="true"/>
    <details key="workspace.zoom.controls" value="true"/>
    <details key="workspace.zoom.wheel" value="true"/>
    <details key="workspace.move.scrollbars" value="true"/>
    <details key="workspace.move.drag" value="true"/>

  </eAnnotations>


  <eClassifiers xsi:type="ecore:EClass" name="WidgetStyle">
    <eAnnotations source="blockly">
      <details key="colour" value="20"/>
      <details key="category" value="Fields"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="visible"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="true">
      <eAnnotations source="ui">
        <details key="label" value="Visible"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="width"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="320">
      <eAnnotations source="blockly">
        <details key="min" value="0"/>
        <details key="max" value="960"/>
      </eAnnotations>
      <eAnnotations source="ui">
        <details key="label" value="Width"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="accentColor"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="#1f6feb">
      <eAnnotations source="blockly">
        <details key="type" value="field_colour"/>
      </eAnnotations>
      <eAnnotations source="ui">
        <details key="label" value="Accent"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>

</ecore:EPackage>
