/**
 * generated by Xtext 2.42.0
 */
package io.github.plortinus.model2blockly.model2Blockly;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Int Option</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link io.github.plortinus.model2blockly.model2Blockly.IntOption#getValue <em>Value</em>}</li>
 * </ul>
 *
 * @see io.github.plortinus.model2blockly.model2Blockly.Model2BlocklyPackage#getIntOption()
 * @model
 * @generated
 */
public interface IntOption extends WorkspaceOption
{
  /**
   * Returns the value of the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value</em>' attribute.
   * @see #setValue(int)
   * @see io.github.plortinus.model2blockly.model2Blockly.Model2BlocklyPackage#getIntOption_Value()
   * @model
   * @generated
   */
  int getValue();

  /**
   * Sets the value of the '{@link io.github.plortinus.model2blockly.model2Blockly.IntOption#getValue <em>Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value</em>' attribute.
   * @see #getValue()
   * @generated
   */
  void setValue(int value);

} // IntOption
