/**
 * generated by Xtext 2.42.0
 */
package io.github.plortinus.model2blockly.model2Blockly;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Reference</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link io.github.plortinus.model2blockly.model2Blockly.Reference#getType <em>Type</em>}</li>
 *   <li>{@link io.github.plortinus.model2blockly.model2Blockly.Reference#getCardinality <em>Cardinality</em>}</li>
 *   <li>{@link io.github.plortinus.model2blockly.model2Blockly.Reference#getOppositeName <em>Opposite Name</em>}</li>
 *   <li>{@link io.github.plortinus.model2blockly.model2Blockly.Reference#isRequired <em>Required</em>}</li>
 *   <li>{@link io.github.plortinus.model2blockly.model2Blockly.Reference#isUnique <em>Unique</em>}</li>
 *   <li>{@link io.github.plortinus.model2blockly.model2Blockly.Reference#isNonUnique <em>Non Unique</em>}</li>
 *   <li>{@link io.github.plortinus.model2blockly.model2Blockly.Reference#isOrdered <em>Ordered</em>}</li>
 *   <li>{@link io.github.plortinus.model2blockly.model2Blockly.Reference#isUnordered <em>Unordered</em>}</li>
 * </ul>
 *
 * @see io.github.plortinus.model2blockly.model2Blockly.Model2BlocklyPackage#getReference()
 * @model
 * @generated
 */
public interface Reference extends Feature
{
  /**
   * Returns the value of the '<em><b>Type</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' reference.
   * @see #setType(ClassDef)
   * @see io.github.plortinus.model2blockly.model2Blockly.Model2BlocklyPackage#getReference_Type()
   * @model
   * @generated
   */
  ClassDef getType();

  /**
   * Sets the value of the '{@link io.github.plortinus.model2blockly.model2Blockly.Reference#getType <em>Type</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' reference.
   * @see #getType()
   * @generated
   */
  void setType(ClassDef value);

  /**
   * Returns the value of the '<em><b>Cardinality</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Cardinality</em>' containment reference.
   * @see #setCardinality(Cardinality)
   * @see io.github.plortinus.model2blockly.model2Blockly.Model2BlocklyPackage#getReference_Cardinality()
   * @model containment="true"
   * @generated
   */
  Cardinality getCardinality();

  /**
   * Sets the value of the '{@link io.github.plortinus.model2blockly.model2Blockly.Reference#getCardinality <em>Cardinality</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Cardinality</em>' containment reference.
   * @see #getCardinality()
   * @generated
   */
  void setCardinality(Cardinality value);

  /**
   * Returns the value of the '<em><b>Opposite Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Opposite Name</em>' attribute.
   * @see #setOppositeName(String)
   * @see io.github.plortinus.model2blockly.model2Blockly.Model2BlocklyPackage#getReference_OppositeName()
   * @model
   * @generated
   */
  String getOppositeName();

  /**
   * Sets the value of the '{@link io.github.plortinus.model2blockly.model2Blockly.Reference#getOppositeName <em>Opposite Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Opposite Name</em>' attribute.
   * @see #getOppositeName()
   * @generated
   */
  void setOppositeName(String value);

  /**
   * Returns the value of the '<em><b>Required</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Required</em>' attribute.
   * @see #setRequired(boolean)
   * @see io.github.plortinus.model2blockly.model2Blockly.Model2BlocklyPackage#getReference_Required()
   * @model
   * @generated
   */
  boolean isRequired();

  /**
   * Sets the value of the '{@link io.github.plortinus.model2blockly.model2Blockly.Reference#isRequired <em>Required</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Required</em>' attribute.
   * @see #isRequired()
   * @generated
   */
  void setRequired(boolean value);

  /**
   * Returns the value of the '<em><b>Unique</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Unique</em>' attribute.
   * @see #setUnique(boolean)
   * @see io.github.plortinus.model2blockly.model2Blockly.Model2BlocklyPackage#getReference_Unique()
   * @model
   * @generated
   */
  boolean isUnique();

  /**
   * Sets the value of the '{@link io.github.plortinus.model2blockly.model2Blockly.Reference#isUnique <em>Unique</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Unique</em>' attribute.
   * @see #isUnique()
   * @generated
   */
  void setUnique(boolean value);

  /**
   * Returns the value of the '<em><b>Non Unique</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Non Unique</em>' attribute.
   * @see #setNonUnique(boolean)
   * @see io.github.plortinus.model2blockly.model2Blockly.Model2BlocklyPackage#getReference_NonUnique()
   * @model
   * @generated
   */
  boolean isNonUnique();

  /**
   * Sets the value of the '{@link io.github.plortinus.model2blockly.model2Blockly.Reference#isNonUnique <em>Non Unique</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Non Unique</em>' attribute.
   * @see #isNonUnique()
   * @generated
   */
  void setNonUnique(boolean value);

  /**
   * Returns the value of the '<em><b>Ordered</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ordered</em>' attribute.
   * @see #setOrdered(boolean)
   * @see io.github.plortinus.model2blockly.model2Blockly.Model2BlocklyPackage#getReference_Ordered()
   * @model
   * @generated
   */
  boolean isOrdered();

  /**
   * Sets the value of the '{@link io.github.plortinus.model2blockly.model2Blockly.Reference#isOrdered <em>Ordered</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ordered</em>' attribute.
   * @see #isOrdered()
   * @generated
   */
  void setOrdered(boolean value);

  /**
   * Returns the value of the '<em><b>Unordered</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Unordered</em>' attribute.
   * @see #setUnordered(boolean)
   * @see io.github.plortinus.model2blockly.model2Blockly.Model2BlocklyPackage#getReference_Unordered()
   * @model
   * @generated
   */
  boolean isUnordered();

  /**
   * Sets the value of the '{@link io.github.plortinus.model2blockly.model2Blockly.Reference#isUnordered <em>Unordered</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Unordered</em>' attribute.
   * @see #isUnordered()
   * @generated
   */
  void setUnordered(boolean value);

} // Reference
