/**
 * generated by Xtext 2.42.0
 */
package io.github.plortinus.model2blockly.model2Blockly;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Validation Def</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link io.github.plortinus.model2blockly.model2Blockly.ValidationDef#getName <em>Name</em>}</li>
 *   <li>{@link io.github.plortinus.model2blockly.model2Blockly.ValidationDef#getTarget <em>Target</em>}</li>
 *   <li>{@link io.github.plortinus.model2blockly.model2Blockly.ValidationDef#getKind <em>Kind</em>}</li>
 *   <li>{@link io.github.plortinus.model2blockly.model2Blockly.ValidationDef#getExpression <em>Expression</em>}</li>
 *   <li>{@link io.github.plortinus.model2blockly.model2Blockly.ValidationDef#getMessage <em>Message</em>}</li>
 * </ul>
 *
 * @see io.github.plortinus.model2blockly.model2Blockly.Model2BlocklyPackage#getValidationDef()
 * @model
 * @generated
 */
public interface ValidationDef extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see io.github.plortinus.model2blockly.model2Blockly.Model2BlocklyPackage#getValidationDef_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link io.github.plortinus.model2blockly.model2Blockly.ValidationDef#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Target</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Target</em>' reference.
   * @see #setTarget(ClassDef)
   * @see io.github.plortinus.model2blockly.model2Blockly.Model2BlocklyPackage#getValidationDef_Target()
   * @model
   * @generated
   */
  ClassDef getTarget();

  /**
   * Sets the value of the '{@link io.github.plortinus.model2blockly.model2Blockly.ValidationDef#getTarget <em>Target</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Target</em>' reference.
   * @see #getTarget()
   * @generated
   */
  void setTarget(ClassDef value);

  /**
   * Returns the value of the '<em><b>Kind</b></em>' attribute.
   * The literals are from the enumeration {@link io.github.plortinus.model2blockly.model2Blockly.ValidationKind}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Kind</em>' attribute.
   * @see io.github.plortinus.model2blockly.model2Blockly.ValidationKind
   * @see #setKind(ValidationKind)
   * @see io.github.plortinus.model2blockly.model2Blockly.Model2BlocklyPackage#getValidationDef_Kind()
   * @model
   * @generated
   */
  ValidationKind getKind();

  /**
   * Sets the value of the '{@link io.github.plortinus.model2blockly.model2Blockly.ValidationDef#getKind <em>Kind</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Kind</em>' attribute.
   * @see io.github.plortinus.model2blockly.model2Blockly.ValidationKind
   * @see #getKind()
   * @generated
   */
  void setKind(ValidationKind value);

  /**
   * Returns the value of the '<em><b>Expression</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Expression</em>' attribute.
   * @see #setExpression(String)
   * @see io.github.plortinus.model2blockly.model2Blockly.Model2BlocklyPackage#getValidationDef_Expression()
   * @model
   * @generated
   */
  String getExpression();

  /**
   * Sets the value of the '{@link io.github.plortinus.model2blockly.model2Blockly.ValidationDef#getExpression <em>Expression</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Expression</em>' attribute.
   * @see #getExpression()
   * @generated
   */
  void setExpression(String value);

  /**
   * Returns the value of the '<em><b>Message</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Message</em>' attribute.
   * @see #setMessage(String)
   * @see io.github.plortinus.model2blockly.model2Blockly.Model2BlocklyPackage#getValidationDef_Message()
   * @model
   * @generated
   */
  String getMessage();

  /**
   * Sets the value of the '{@link io.github.plortinus.model2blockly.model2Blockly.ValidationDef#getMessage <em>Message</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Message</em>' attribute.
   * @see #getMessage()
   * @generated
   */
  void setMessage(String value);

} // ValidationDef
