/**
 * generated by Xtext 2.42.0
 */
package io.github.plortinus.model2blockly.model2Blockly.impl;

import io.github.plortinus.model2blockly.model2Blockly.Cardinality;
import io.github.plortinus.model2blockly.model2Blockly.ClassDef;
import io.github.plortinus.model2blockly.model2Blockly.Model2BlocklyPackage;
import io.github.plortinus.model2blockly.model2Blockly.Reference;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Reference</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link io.github.plortinus.model2blockly.model2Blockly.impl.ReferenceImpl#getType <em>Type</em>}</li>
 *   <li>{@link io.github.plortinus.model2blockly.model2Blockly.impl.ReferenceImpl#getCardinality <em>Cardinality</em>}</li>
 *   <li>{@link io.github.plortinus.model2blockly.model2Blockly.impl.ReferenceImpl#getOppositeName <em>Opposite Name</em>}</li>
 *   <li>{@link io.github.plortinus.model2blockly.model2Blockly.impl.ReferenceImpl#isRequired <em>Required</em>}</li>
 *   <li>{@link io.github.plortinus.model2blockly.model2Blockly.impl.ReferenceImpl#isUnique <em>Unique</em>}</li>
 *   <li>{@link io.github.plortinus.model2blockly.model2Blockly.impl.ReferenceImpl#isNonUnique <em>Non Unique</em>}</li>
 *   <li>{@link io.github.plortinus.model2blockly.model2Blockly.impl.ReferenceImpl#isOrdered <em>Ordered</em>}</li>
 *   <li>{@link io.github.plortinus.model2blockly.model2Blockly.impl.ReferenceImpl#isUnordered <em>Unordered</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ReferenceImpl extends FeatureImpl implements Reference
{
  /**
   * The cached value of the '{@link #getType() <em>Type</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getType()
   * @generated
   * @ordered
   */
  protected ClassDef type;

  /**
   * The cached value of the '{@link #getCardinality() <em>Cardinality</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCardinality()
   * @generated
   * @ordered
   */
  protected Cardinality cardinality;

  /**
   * The default value of the '{@link #getOppositeName() <em>Opposite Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getOppositeName()
   * @generated
   * @ordered
   */
  protected static final String OPPOSITE_NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getOppositeName() <em>Opposite Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getOppositeName()
   * @generated
   * @ordered
   */
  protected String oppositeName = OPPOSITE_NAME_EDEFAULT;

  /**
   * The default value of the '{@link #isRequired() <em>Required</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isRequired()
   * @generated
   * @ordered
   */
  protected static final boolean REQUIRED_EDEFAULT = false;

  /**
   * The cached value of the '{@link #isRequired() <em>Required</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isRequired()
   * @generated
   * @ordered
   */
  protected boolean required = REQUIRED_EDEFAULT;

  /**
   * The default value of the '{@link #isUnique() <em>Unique</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isUnique()
   * @generated
   * @ordered
   */
  protected static final boolean UNIQUE_EDEFAULT = false;

  /**
   * The cached value of the '{@link #isUnique() <em>Unique</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isUnique()
   * @generated
   * @ordered
   */
  protected boolean unique = UNIQUE_EDEFAULT;

  /**
   * The default value of the '{@link #isNonUnique() <em>Non Unique</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isNonUnique()
   * @generated
   * @ordered
   */
  protected static final boolean NON_UNIQUE_EDEFAULT = false;

  /**
   * The cached value of the '{@link #isNonUnique() <em>Non Unique</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isNonUnique()
   * @generated
   * @ordered
   */
  protected boolean nonUnique = NON_UNIQUE_EDEFAULT;

  /**
   * The default value of the '{@link #isOrdered() <em>Ordered</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isOrdered()
   * @generated
   * @ordered
   */
  protected static final boolean ORDERED_EDEFAULT = false;

  /**
   * The cached value of the '{@link #isOrdered() <em>Ordered</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isOrdered()
   * @generated
   * @ordered
   */
  protected boolean ordered = ORDERED_EDEFAULT;

  /**
   * The default value of the '{@link #isUnordered() <em>Unordered</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isUnordered()
   * @generated
   * @ordered
   */
  protected static final boolean UNORDERED_EDEFAULT = false;

  /**
   * The cached value of the '{@link #isUnordered() <em>Unordered</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isUnordered()
   * @generated
   * @ordered
   */
  protected boolean unordered = UNORDERED_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ReferenceImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return Model2BlocklyPackage.Literals.REFERENCE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ClassDef getType()
  {
    if (type != null && type.eIsProxy())
    {
      InternalEObject oldType = (InternalEObject)type;
      type = (ClassDef)eResolveProxy(oldType);
      if (type != oldType)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, Model2BlocklyPackage.REFERENCE__TYPE, oldType, type));
      }
    }
    return type;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ClassDef basicGetType()
  {
    return type;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setType(ClassDef newType)
  {
    ClassDef oldType = type;
    type = newType;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, Model2BlocklyPackage.REFERENCE__TYPE, oldType, type));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Cardinality getCardinality()
  {
    return cardinality;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetCardinality(Cardinality newCardinality, NotificationChain msgs)
  {
    Cardinality oldCardinality = cardinality;
    cardinality = newCardinality;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, Model2BlocklyPackage.REFERENCE__CARDINALITY, oldCardinality, newCardinality);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setCardinality(Cardinality newCardinality)
  {
    if (newCardinality != cardinality)
    {
      NotificationChain msgs = null;
      if (cardinality != null)
        msgs = ((InternalEObject)cardinality).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - Model2BlocklyPackage.REFERENCE__CARDINALITY, null, msgs);
      if (newCardinality != null)
        msgs = ((InternalEObject)newCardinality).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - Model2BlocklyPackage.REFERENCE__CARDINALITY, null, msgs);
      msgs = basicSetCardinality(newCardinality, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, Model2BlocklyPackage.REFERENCE__CARDINALITY, newCardinality, newCardinality));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getOppositeName()
  {
    return oppositeName;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setOppositeName(String newOppositeName)
  {
    String oldOppositeName = oppositeName;
    oppositeName = newOppositeName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, Model2BlocklyPackage.REFERENCE__OPPOSITE_NAME, oldOppositeName, oppositeName));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean isRequired()
  {
    return required;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setRequired(boolean newRequired)
  {
    boolean oldRequired = required;
    required = newRequired;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, Model2BlocklyPackage.REFERENCE__REQUIRED, oldRequired, required));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean isUnique()
  {
    return unique;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setUnique(boolean newUnique)
  {
    boolean oldUnique = unique;
    unique = newUnique;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, Model2BlocklyPackage.REFERENCE__UNIQUE, oldUnique, unique));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean isNonUnique()
  {
    return nonUnique;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setNonUnique(boolean newNonUnique)
  {
    boolean oldNonUnique = nonUnique;
    nonUnique = newNonUnique;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, Model2BlocklyPackage.REFERENCE__NON_UNIQUE, oldNonUnique, nonUnique));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean isOrdered()
  {
    return ordered;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setOrdered(boolean newOrdered)
  {
    boolean oldOrdered = ordered;
    ordered = newOrdered;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, Model2BlocklyPackage.REFERENCE__ORDERED, oldOrdered, ordered));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean isUnordered()
  {
    return unordered;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setUnordered(boolean newUnordered)
  {
    boolean oldUnordered = unordered;
    unordered = newUnordered;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, Model2BlocklyPackage.REFERENCE__UNORDERED, oldUnordered, unordered));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case Model2BlocklyPackage.REFERENCE__CARDINALITY:
        return basicSetCardinality(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case Model2BlocklyPackage.REFERENCE__TYPE:
        if (resolve) return getType();
        return basicGetType();
      case Model2BlocklyPackage.REFERENCE__CARDINALITY:
        return getCardinality();
      case Model2BlocklyPackage.REFERENCE__OPPOSITE_NAME:
        return getOppositeName();
      case Model2BlocklyPackage.REFERENCE__REQUIRED:
        return isRequired();
      case Model2BlocklyPackage.REFERENCE__UNIQUE:
        return isUnique();
      case Model2BlocklyPackage.REFERENCE__NON_UNIQUE:
        return isNonUnique();
      case Model2BlocklyPackage.REFERENCE__ORDERED:
        return isOrdered();
      case Model2BlocklyPackage.REFERENCE__UNORDERED:
        return isUnordered();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case Model2BlocklyPackage.REFERENCE__TYPE:
        setType((ClassDef)newValue);
        return;
      case Model2BlocklyPackage.REFERENCE__CARDINALITY:
        setCardinality((Cardinality)newValue);
        return;
      case Model2BlocklyPackage.REFERENCE__OPPOSITE_NAME:
        setOppositeName((String)newValue);
        return;
      case Model2BlocklyPackage.REFERENCE__REQUIRED:
        setRequired((Boolean)newValue);
        return;
      case Model2BlocklyPackage.REFERENCE__UNIQUE:
        setUnique((Boolean)newValue);
        return;
      case Model2BlocklyPackage.REFERENCE__NON_UNIQUE:
        setNonUnique((Boolean)newValue);
        return;
      case Model2BlocklyPackage.REFERENCE__ORDERED:
        setOrdered((Boolean)newValue);
        return;
      case Model2BlocklyPackage.REFERENCE__UNORDERED:
        setUnordered((Boolean)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case Model2BlocklyPackage.REFERENCE__TYPE:
        setType((ClassDef)null);
        return;
      case Model2BlocklyPackage.REFERENCE__CARDINALITY:
        setCardinality((Cardinality)null);
        return;
      case Model2BlocklyPackage.REFERENCE__OPPOSITE_NAME:
        setOppositeName(OPPOSITE_NAME_EDEFAULT);
        return;
      case Model2BlocklyPackage.REFERENCE__REQUIRED:
        setRequired(REQUIRED_EDEFAULT);
        return;
      case Model2BlocklyPackage.REFERENCE__UNIQUE:
        setUnique(UNIQUE_EDEFAULT);
        return;
      case Model2BlocklyPackage.REFERENCE__NON_UNIQUE:
        setNonUnique(NON_UNIQUE_EDEFAULT);
        return;
      case Model2BlocklyPackage.REFERENCE__ORDERED:
        setOrdered(ORDERED_EDEFAULT);
        return;
      case Model2BlocklyPackage.REFERENCE__UNORDERED:
        setUnordered(UNORDERED_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case Model2BlocklyPackage.REFERENCE__TYPE:
        return type != null;
      case Model2BlocklyPackage.REFERENCE__CARDINALITY:
        return cardinality != null;
      case Model2BlocklyPackage.REFERENCE__OPPOSITE_NAME:
        return OPPOSITE_NAME_EDEFAULT == null ? oppositeName != null : !OPPOSITE_NAME_EDEFAULT.equals(oppositeName);
      case Model2BlocklyPackage.REFERENCE__REQUIRED:
        return required != REQUIRED_EDEFAULT;
      case Model2BlocklyPackage.REFERENCE__UNIQUE:
        return unique != UNIQUE_EDEFAULT;
      case Model2BlocklyPackage.REFERENCE__NON_UNIQUE:
        return nonUnique != NON_UNIQUE_EDEFAULT;
      case Model2BlocklyPackage.REFERENCE__ORDERED:
        return ordered != ORDERED_EDEFAULT;
      case Model2BlocklyPackage.REFERENCE__UNORDERED:
        return unordered != UNORDERED_EDEFAULT;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (oppositeName: ");
    result.append(oppositeName);
    result.append(", required: ");
    result.append(required);
    result.append(", unique: ");
    result.append(unique);
    result.append(", nonUnique: ");
    result.append(nonUnique);
    result.append(", ordered: ");
    result.append(ordered);
    result.append(", unordered: ");
    result.append(unordered);
    result.append(')');
    return result.toString();
  }

} //ReferenceImpl
