/**
 * generated by Xtext 2.42.0
 */
package io.github.plortinus.model2blockly.model2Blockly.impl;

import io.github.plortinus.model2blockly.model2Blockly.Attribute;
import io.github.plortinus.model2blockly.model2Blockly.AttributeType;
import io.github.plortinus.model2blockly.model2Blockly.Cardinality;
import io.github.plortinus.model2blockly.model2Blockly.Model2BlocklyPackage;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Attribute</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link io.github.plortinus.model2blockly.model2Blockly.impl.AttributeImpl#getType <em>Type</em>}</li>
 *   <li>{@link io.github.plortinus.model2blockly.model2Blockly.impl.AttributeImpl#getCardinality <em>Cardinality</em>}</li>
 *   <li>{@link io.github.plortinus.model2blockly.model2Blockly.impl.AttributeImpl#getDefaultValue <em>Default Value</em>}</li>
 *   <li>{@link io.github.plortinus.model2blockly.model2Blockly.impl.AttributeImpl#getMin <em>Min</em>}</li>
 *   <li>{@link io.github.plortinus.model2blockly.model2Blockly.impl.AttributeImpl#getMax <em>Max</em>}</li>
 *   <li>{@link io.github.plortinus.model2blockly.model2Blockly.impl.AttributeImpl#getImageUrl <em>Image Url</em>}</li>
 *   <li>{@link io.github.plortinus.model2blockly.model2Blockly.impl.AttributeImpl#getImageWidth <em>Image Width</em>}</li>
 *   <li>{@link io.github.plortinus.model2blockly.model2Blockly.impl.AttributeImpl#getImageHeight <em>Image Height</em>}</li>
 *   <li>{@link io.github.plortinus.model2blockly.model2Blockly.impl.AttributeImpl#getImageAlt <em>Image Alt</em>}</li>
 *   <li>{@link io.github.plortinus.model2blockly.model2Blockly.impl.AttributeImpl#isRequired <em>Required</em>}</li>
 *   <li>{@link io.github.plortinus.model2blockly.model2Blockly.impl.AttributeImpl#isId <em>Id</em>}</li>
 *   <li>{@link io.github.plortinus.model2blockly.model2Blockly.impl.AttributeImpl#isUnique <em>Unique</em>}</li>
 *   <li>{@link io.github.plortinus.model2blockly.model2Blockly.impl.AttributeImpl#isNonUnique <em>Non Unique</em>}</li>
 *   <li>{@link io.github.plortinus.model2blockly.model2Blockly.impl.AttributeImpl#isOrdered <em>Ordered</em>}</li>
 *   <li>{@link io.github.plortinus.model2blockly.model2Blockly.impl.AttributeImpl#isUnordered <em>Unordered</em>}</li>
 * </ul>
 *
 * @generated
 */
public class AttributeImpl extends FeatureImpl implements Attribute
{
  /**
   * The cached value of the '{@link #getType() <em>Type</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getType()
   * @generated
   * @ordered
   */
  protected AttributeType type;

  /**
   * The cached value of the '{@link #getCardinality() <em>Cardinality</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCardinality()
   * @generated
   * @ordered
   */
  protected Cardinality cardinality;

  /**
   * The default value of the '{@link #getDefaultValue() <em>Default Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDefaultValue()
   * @generated
   * @ordered
   */
  protected static final String DEFAULT_VALUE_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getDefaultValue() <em>Default Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDefaultValue()
   * @generated
   * @ordered
   */
  protected String defaultValue = DEFAULT_VALUE_EDEFAULT;

  /**
   * The default value of the '{@link #getMin() <em>Min</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getMin()
   * @generated
   * @ordered
   */
  protected static final String MIN_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getMin() <em>Min</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getMin()
   * @generated
   * @ordered
   */
  protected String min = MIN_EDEFAULT;

  /**
   * The default value of the '{@link #getMax() <em>Max</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getMax()
   * @generated
   * @ordered
   */
  protected static final String MAX_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getMax() <em>Max</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getMax()
   * @generated
   * @ordered
   */
  protected String max = MAX_EDEFAULT;

  /**
   * The default value of the '{@link #getImageUrl() <em>Image Url</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getImageUrl()
   * @generated
   * @ordered
   */
  protected static final String IMAGE_URL_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getImageUrl() <em>Image Url</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getImageUrl()
   * @generated
   * @ordered
   */
  protected String imageUrl = IMAGE_URL_EDEFAULT;

  /**
   * The default value of the '{@link #getImageWidth() <em>Image Width</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getImageWidth()
   * @generated
   * @ordered
   */
  protected static final int IMAGE_WIDTH_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getImageWidth() <em>Image Width</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getImageWidth()
   * @generated
   * @ordered
   */
  protected int imageWidth = IMAGE_WIDTH_EDEFAULT;

  /**
   * The default value of the '{@link #getImageHeight() <em>Image Height</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getImageHeight()
   * @generated
   * @ordered
   */
  protected static final int IMAGE_HEIGHT_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getImageHeight() <em>Image Height</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getImageHeight()
   * @generated
   * @ordered
   */
  protected int imageHeight = IMAGE_HEIGHT_EDEFAULT;

  /**
   * The default value of the '{@link #getImageAlt() <em>Image Alt</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getImageAlt()
   * @generated
   * @ordered
   */
  protected static final String IMAGE_ALT_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getImageAlt() <em>Image Alt</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getImageAlt()
   * @generated
   * @ordered
   */
  protected String imageAlt = IMAGE_ALT_EDEFAULT;

  /**
   * The default value of the '{@link #isRequired() <em>Required</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isRequired()
   * @generated
   * @ordered
   */
  protected static final boolean REQUIRED_EDEFAULT = false;

  /**
   * The cached value of the '{@link #isRequired() <em>Required</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isRequired()
   * @generated
   * @ordered
   */
  protected boolean required = REQUIRED_EDEFAULT;

  /**
   * The default value of the '{@link #isId() <em>Id</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isId()
   * @generated
   * @ordered
   */
  protected static final boolean ID_EDEFAULT = false;

  /**
   * The cached value of the '{@link #isId() <em>Id</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isId()
   * @generated
   * @ordered
   */
  protected boolean id = ID_EDEFAULT;

  /**
   * The default value of the '{@link #isUnique() <em>Unique</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isUnique()
   * @generated
   * @ordered
   */
  protected static final boolean UNIQUE_EDEFAULT = false;

  /**
   * The cached value of the '{@link #isUnique() <em>Unique</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isUnique()
   * @generated
   * @ordered
   */
  protected boolean unique = UNIQUE_EDEFAULT;

  /**
   * The default value of the '{@link #isNonUnique() <em>Non Unique</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isNonUnique()
   * @generated
   * @ordered
   */
  protected static final boolean NON_UNIQUE_EDEFAULT = false;

  /**
   * The cached value of the '{@link #isNonUnique() <em>Non Unique</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isNonUnique()
   * @generated
   * @ordered
   */
  protected boolean nonUnique = NON_UNIQUE_EDEFAULT;

  /**
   * The default value of the '{@link #isOrdered() <em>Ordered</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isOrdered()
   * @generated
   * @ordered
   */
  protected static final boolean ORDERED_EDEFAULT = false;

  /**
   * The cached value of the '{@link #isOrdered() <em>Ordered</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isOrdered()
   * @generated
   * @ordered
   */
  protected boolean ordered = ORDERED_EDEFAULT;

  /**
   * The default value of the '{@link #isUnordered() <em>Unordered</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isUnordered()
   * @generated
   * @ordered
   */
  protected static final boolean UNORDERED_EDEFAULT = false;

  /**
   * The cached value of the '{@link #isUnordered() <em>Unordered</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isUnordered()
   * @generated
   * @ordered
   */
  protected boolean unordered = UNORDERED_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected AttributeImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return Model2BlocklyPackage.Literals.ATTRIBUTE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public AttributeType getType()
  {
    return type;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetType(AttributeType newType, NotificationChain msgs)
  {
    AttributeType oldType = type;
    type = newType;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, Model2BlocklyPackage.ATTRIBUTE__TYPE, oldType, newType);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setType(AttributeType newType)
  {
    if (newType != type)
    {
      NotificationChain msgs = null;
      if (type != null)
        msgs = ((InternalEObject)type).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - Model2BlocklyPackage.ATTRIBUTE__TYPE, null, msgs);
      if (newType != null)
        msgs = ((InternalEObject)newType).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - Model2BlocklyPackage.ATTRIBUTE__TYPE, null, msgs);
      msgs = basicSetType(newType, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, Model2BlocklyPackage.ATTRIBUTE__TYPE, newType, newType));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Cardinality getCardinality()
  {
    return cardinality;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetCardinality(Cardinality newCardinality, NotificationChain msgs)
  {
    Cardinality oldCardinality = cardinality;
    cardinality = newCardinality;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, Model2BlocklyPackage.ATTRIBUTE__CARDINALITY, oldCardinality, newCardinality);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setCardinality(Cardinality newCardinality)
  {
    if (newCardinality != cardinality)
    {
      NotificationChain msgs = null;
      if (cardinality != null)
        msgs = ((InternalEObject)cardinality).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - Model2BlocklyPackage.ATTRIBUTE__CARDINALITY, null, msgs);
      if (newCardinality != null)
        msgs = ((InternalEObject)newCardinality).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - Model2BlocklyPackage.ATTRIBUTE__CARDINALITY, null, msgs);
      msgs = basicSetCardinality(newCardinality, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, Model2BlocklyPackage.ATTRIBUTE__CARDINALITY, newCardinality, newCardinality));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getDefaultValue()
  {
    return defaultValue;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setDefaultValue(String newDefaultValue)
  {
    String oldDefaultValue = defaultValue;
    defaultValue = newDefaultValue;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, Model2BlocklyPackage.ATTRIBUTE__DEFAULT_VALUE, oldDefaultValue, defaultValue));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getMin()
  {
    return min;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setMin(String newMin)
  {
    String oldMin = min;
    min = newMin;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, Model2BlocklyPackage.ATTRIBUTE__MIN, oldMin, min));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getMax()
  {
    return max;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setMax(String newMax)
  {
    String oldMax = max;
    max = newMax;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, Model2BlocklyPackage.ATTRIBUTE__MAX, oldMax, max));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getImageUrl()
  {
    return imageUrl;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setImageUrl(String newImageUrl)
  {
    String oldImageUrl = imageUrl;
    imageUrl = newImageUrl;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, Model2BlocklyPackage.ATTRIBUTE__IMAGE_URL, oldImageUrl, imageUrl));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getImageWidth()
  {
    return imageWidth;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setImageWidth(int newImageWidth)
  {
    int oldImageWidth = imageWidth;
    imageWidth = newImageWidth;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, Model2BlocklyPackage.ATTRIBUTE__IMAGE_WIDTH, oldImageWidth, imageWidth));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getImageHeight()
  {
    return imageHeight;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setImageHeight(int newImageHeight)
  {
    int oldImageHeight = imageHeight;
    imageHeight = newImageHeight;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, Model2BlocklyPackage.ATTRIBUTE__IMAGE_HEIGHT, oldImageHeight, imageHeight));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getImageAlt()
  {
    return imageAlt;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setImageAlt(String newImageAlt)
  {
    String oldImageAlt = imageAlt;
    imageAlt = newImageAlt;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, Model2BlocklyPackage.ATTRIBUTE__IMAGE_ALT, oldImageAlt, imageAlt));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean isRequired()
  {
    return required;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setRequired(boolean newRequired)
  {
    boolean oldRequired = required;
    required = newRequired;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, Model2BlocklyPackage.ATTRIBUTE__REQUIRED, oldRequired, required));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean isId()
  {
    return id;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setId(boolean newId)
  {
    boolean oldId = id;
    id = newId;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, Model2BlocklyPackage.ATTRIBUTE__ID, oldId, id));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean isUnique()
  {
    return unique;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setUnique(boolean newUnique)
  {
    boolean oldUnique = unique;
    unique = newUnique;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, Model2BlocklyPackage.ATTRIBUTE__UNIQUE, oldUnique, unique));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean isNonUnique()
  {
    return nonUnique;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setNonUnique(boolean newNonUnique)
  {
    boolean oldNonUnique = nonUnique;
    nonUnique = newNonUnique;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, Model2BlocklyPackage.ATTRIBUTE__NON_UNIQUE, oldNonUnique, nonUnique));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean isOrdered()
  {
    return ordered;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setOrdered(boolean newOrdered)
  {
    boolean oldOrdered = ordered;
    ordered = newOrdered;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, Model2BlocklyPackage.ATTRIBUTE__ORDERED, oldOrdered, ordered));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean isUnordered()
  {
    return unordered;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setUnordered(boolean newUnordered)
  {
    boolean oldUnordered = unordered;
    unordered = newUnordered;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, Model2BlocklyPackage.ATTRIBUTE__UNORDERED, oldUnordered, unordered));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case Model2BlocklyPackage.ATTRIBUTE__TYPE:
        return basicSetType(null, msgs);
      case Model2BlocklyPackage.ATTRIBUTE__CARDINALITY:
        return basicSetCardinality(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case Model2BlocklyPackage.ATTRIBUTE__TYPE:
        return getType();
      case Model2BlocklyPackage.ATTRIBUTE__CARDINALITY:
        return getCardinality();
      case Model2BlocklyPackage.ATTRIBUTE__DEFAULT_VALUE:
        return getDefaultValue();
      case Model2BlocklyPackage.ATTRIBUTE__MIN:
        return getMin();
      case Model2BlocklyPackage.ATTRIBUTE__MAX:
        return getMax();
      case Model2BlocklyPackage.ATTRIBUTE__IMAGE_URL:
        return getImageUrl();
      case Model2BlocklyPackage.ATTRIBUTE__IMAGE_WIDTH:
        return getImageWidth();
      case Model2BlocklyPackage.ATTRIBUTE__IMAGE_HEIGHT:
        return getImageHeight();
      case Model2BlocklyPackage.ATTRIBUTE__IMAGE_ALT:
        return getImageAlt();
      case Model2BlocklyPackage.ATTRIBUTE__REQUIRED:
        return isRequired();
      case Model2BlocklyPackage.ATTRIBUTE__ID:
        return isId();
      case Model2BlocklyPackage.ATTRIBUTE__UNIQUE:
        return isUnique();
      case Model2BlocklyPackage.ATTRIBUTE__NON_UNIQUE:
        return isNonUnique();
      case Model2BlocklyPackage.ATTRIBUTE__ORDERED:
        return isOrdered();
      case Model2BlocklyPackage.ATTRIBUTE__UNORDERED:
        return isUnordered();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case Model2BlocklyPackage.ATTRIBUTE__TYPE:
        setType((AttributeType)newValue);
        return;
      case Model2BlocklyPackage.ATTRIBUTE__CARDINALITY:
        setCardinality((Cardinality)newValue);
        return;
      case Model2BlocklyPackage.ATTRIBUTE__DEFAULT_VALUE:
        setDefaultValue((String)newValue);
        return;
      case Model2BlocklyPackage.ATTRIBUTE__MIN:
        setMin((String)newValue);
        return;
      case Model2BlocklyPackage.ATTRIBUTE__MAX:
        setMax((String)newValue);
        return;
      case Model2BlocklyPackage.ATTRIBUTE__IMAGE_URL:
        setImageUrl((String)newValue);
        return;
      case Model2BlocklyPackage.ATTRIBUTE__IMAGE_WIDTH:
        setImageWidth((Integer)newValue);
        return;
      case Model2BlocklyPackage.ATTRIBUTE__IMAGE_HEIGHT:
        setImageHeight((Integer)newValue);
        return;
      case Model2BlocklyPackage.ATTRIBUTE__IMAGE_ALT:
        setImageAlt((String)newValue);
        return;
      case Model2BlocklyPackage.ATTRIBUTE__REQUIRED:
        setRequired((Boolean)newValue);
        return;
      case Model2BlocklyPackage.ATTRIBUTE__ID:
        setId((Boolean)newValue);
        return;
      case Model2BlocklyPackage.ATTRIBUTE__UNIQUE:
        setUnique((Boolean)newValue);
        return;
      case Model2BlocklyPackage.ATTRIBUTE__NON_UNIQUE:
        setNonUnique((Boolean)newValue);
        return;
      case Model2BlocklyPackage.ATTRIBUTE__ORDERED:
        setOrdered((Boolean)newValue);
        return;
      case Model2BlocklyPackage.ATTRIBUTE__UNORDERED:
        setUnordered((Boolean)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case Model2BlocklyPackage.ATTRIBUTE__TYPE:
        setType((AttributeType)null);
        return;
      case Model2BlocklyPackage.ATTRIBUTE__CARDINALITY:
        setCardinality((Cardinality)null);
        return;
      case Model2BlocklyPackage.ATTRIBUTE__DEFAULT_VALUE:
        setDefaultValue(DEFAULT_VALUE_EDEFAULT);
        return;
      case Model2BlocklyPackage.ATTRIBUTE__MIN:
        setMin(MIN_EDEFAULT);
        return;
      case Model2BlocklyPackage.ATTRIBUTE__MAX:
        setMax(MAX_EDEFAULT);
        return;
      case Model2BlocklyPackage.ATTRIBUTE__IMAGE_URL:
        setImageUrl(IMAGE_URL_EDEFAULT);
        return;
      case Model2BlocklyPackage.ATTRIBUTE__IMAGE_WIDTH:
        setImageWidth(IMAGE_WIDTH_EDEFAULT);
        return;
      case Model2BlocklyPackage.ATTRIBUTE__IMAGE_HEIGHT:
        setImageHeight(IMAGE_HEIGHT_EDEFAULT);
        return;
      case Model2BlocklyPackage.ATTRIBUTE__IMAGE_ALT:
        setImageAlt(IMAGE_ALT_EDEFAULT);
        return;
      case Model2BlocklyPackage.ATTRIBUTE__REQUIRED:
        setRequired(REQUIRED_EDEFAULT);
        return;
      case Model2BlocklyPackage.ATTRIBUTE__ID:
        setId(ID_EDEFAULT);
        return;
      case Model2BlocklyPackage.ATTRIBUTE__UNIQUE:
        setUnique(UNIQUE_EDEFAULT);
        return;
      case Model2BlocklyPackage.ATTRIBUTE__NON_UNIQUE:
        setNonUnique(NON_UNIQUE_EDEFAULT);
        return;
      case Model2BlocklyPackage.ATTRIBUTE__ORDERED:
        setOrdered(ORDERED_EDEFAULT);
        return;
      case Model2BlocklyPackage.ATTRIBUTE__UNORDERED:
        setUnordered(UNORDERED_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case Model2BlocklyPackage.ATTRIBUTE__TYPE:
        return type != null;
      case Model2BlocklyPackage.ATTRIBUTE__CARDINALITY:
        return cardinality != null;
      case Model2BlocklyPackage.ATTRIBUTE__DEFAULT_VALUE:
        return DEFAULT_VALUE_EDEFAULT == null ? defaultValue != null : !DEFAULT_VALUE_EDEFAULT.equals(defaultValue);
      case Model2BlocklyPackage.ATTRIBUTE__MIN:
        return MIN_EDEFAULT == null ? min != null : !MIN_EDEFAULT.equals(min);
      case Model2BlocklyPackage.ATTRIBUTE__MAX:
        return MAX_EDEFAULT == null ? max != null : !MAX_EDEFAULT.equals(max);
      case Model2BlocklyPackage.ATTRIBUTE__IMAGE_URL:
        return IMAGE_URL_EDEFAULT == null ? imageUrl != null : !IMAGE_URL_EDEFAULT.equals(imageUrl);
      case Model2BlocklyPackage.ATTRIBUTE__IMAGE_WIDTH:
        return imageWidth != IMAGE_WIDTH_EDEFAULT;
      case Model2BlocklyPackage.ATTRIBUTE__IMAGE_HEIGHT:
        return imageHeight != IMAGE_HEIGHT_EDEFAULT;
      case Model2BlocklyPackage.ATTRIBUTE__IMAGE_ALT:
        return IMAGE_ALT_EDEFAULT == null ? imageAlt != null : !IMAGE_ALT_EDEFAULT.equals(imageAlt);
      case Model2BlocklyPackage.ATTRIBUTE__REQUIRED:
        return required != REQUIRED_EDEFAULT;
      case Model2BlocklyPackage.ATTRIBUTE__ID:
        return id != ID_EDEFAULT;
      case Model2BlocklyPackage.ATTRIBUTE__UNIQUE:
        return unique != UNIQUE_EDEFAULT;
      case Model2BlocklyPackage.ATTRIBUTE__NON_UNIQUE:
        return nonUnique != NON_UNIQUE_EDEFAULT;
      case Model2BlocklyPackage.ATTRIBUTE__ORDERED:
        return ordered != ORDERED_EDEFAULT;
      case Model2BlocklyPackage.ATTRIBUTE__UNORDERED:
        return unordered != UNORDERED_EDEFAULT;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (defaultValue: ");
    result.append(defaultValue);
    result.append(", min: ");
    result.append(min);
    result.append(", max: ");
    result.append(max);
    result.append(", imageUrl: ");
    result.append(imageUrl);
    result.append(", imageWidth: ");
    result.append(imageWidth);
    result.append(", imageHeight: ");
    result.append(imageHeight);
    result.append(", imageAlt: ");
    result.append(imageAlt);
    result.append(", required: ");
    result.append(required);
    result.append(", id: ");
    result.append(id);
    result.append(", unique: ");
    result.append(unique);
    result.append(", nonUnique: ");
    result.append(nonUnique);
    result.append(", ordered: ");
    result.append(ordered);
    result.append(", unordered: ");
    result.append(unordered);
    result.append(')');
    return result.toString();
  }

} //AttributeImpl
