/**
 * generated by Xtext 2.42.0
 */
package io.github.plortinus.model2blockly.model2Blockly.impl;

import io.github.plortinus.model2blockly.model2Blockly.CategoryDef;
import io.github.plortinus.model2blockly.model2Blockly.Model2BlocklyPackage;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Category Def</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link io.github.plortinus.model2blockly.model2Blockly.impl.CategoryDefImpl#getName <em>Name</em>}</li>
 *   <li>{@link io.github.plortinus.model2blockly.model2Blockly.impl.CategoryDefImpl#getLabel <em>Label</em>}</li>
 *   <li>{@link io.github.plortinus.model2blockly.model2Blockly.impl.CategoryDefImpl#getColour <em>Colour</em>}</li>
 *   <li>{@link io.github.plortinus.model2blockly.model2Blockly.impl.CategoryDefImpl#getSubcategories <em>Subcategories</em>}</li>
 * </ul>
 *
 * @generated
 */
public class CategoryDefImpl extends MinimalEObjectImpl.Container implements CategoryDef
{
  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The default value of the '{@link #getLabel() <em>Label</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLabel()
   * @generated
   * @ordered
   */
  protected static final String LABEL_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getLabel() <em>Label</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLabel()
   * @generated
   * @ordered
   */
  protected String label = LABEL_EDEFAULT;

  /**
   * The default value of the '{@link #getColour() <em>Colour</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getColour()
   * @generated
   * @ordered
   */
  protected static final int COLOUR_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getColour() <em>Colour</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getColour()
   * @generated
   * @ordered
   */
  protected int colour = COLOUR_EDEFAULT;

  /**
   * The cached value of the '{@link #getSubcategories() <em>Subcategories</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSubcategories()
   * @generated
   * @ordered
   */
  protected EList<CategoryDef> subcategories;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected CategoryDefImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return Model2BlocklyPackage.Literals.CATEGORY_DEF;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, Model2BlocklyPackage.CATEGORY_DEF__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getLabel()
  {
    return label;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setLabel(String newLabel)
  {
    String oldLabel = label;
    label = newLabel;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, Model2BlocklyPackage.CATEGORY_DEF__LABEL, oldLabel, label));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getColour()
  {
    return colour;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setColour(int newColour)
  {
    int oldColour = colour;
    colour = newColour;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, Model2BlocklyPackage.CATEGORY_DEF__COLOUR, oldColour, colour));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<CategoryDef> getSubcategories()
  {
    if (subcategories == null)
    {
      subcategories = new EObjectContainmentEList<CategoryDef>(CategoryDef.class, this, Model2BlocklyPackage.CATEGORY_DEF__SUBCATEGORIES);
    }
    return subcategories;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case Model2BlocklyPackage.CATEGORY_DEF__SUBCATEGORIES:
        return ((InternalEList<?>)getSubcategories()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case Model2BlocklyPackage.CATEGORY_DEF__NAME:
        return getName();
      case Model2BlocklyPackage.CATEGORY_DEF__LABEL:
        return getLabel();
      case Model2BlocklyPackage.CATEGORY_DEF__COLOUR:
        return getColour();
      case Model2BlocklyPackage.CATEGORY_DEF__SUBCATEGORIES:
        return getSubcategories();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case Model2BlocklyPackage.CATEGORY_DEF__NAME:
        setName((String)newValue);
        return;
      case Model2BlocklyPackage.CATEGORY_DEF__LABEL:
        setLabel((String)newValue);
        return;
      case Model2BlocklyPackage.CATEGORY_DEF__COLOUR:
        setColour((Integer)newValue);
        return;
      case Model2BlocklyPackage.CATEGORY_DEF__SUBCATEGORIES:
        getSubcategories().clear();
        getSubcategories().addAll((Collection<? extends CategoryDef>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case Model2BlocklyPackage.CATEGORY_DEF__NAME:
        setName(NAME_EDEFAULT);
        return;
      case Model2BlocklyPackage.CATEGORY_DEF__LABEL:
        setLabel(LABEL_EDEFAULT);
        return;
      case Model2BlocklyPackage.CATEGORY_DEF__COLOUR:
        setColour(COLOUR_EDEFAULT);
        return;
      case Model2BlocklyPackage.CATEGORY_DEF__SUBCATEGORIES:
        getSubcategories().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case Model2BlocklyPackage.CATEGORY_DEF__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case Model2BlocklyPackage.CATEGORY_DEF__LABEL:
        return LABEL_EDEFAULT == null ? label != null : !LABEL_EDEFAULT.equals(label);
      case Model2BlocklyPackage.CATEGORY_DEF__COLOUR:
        return colour != COLOUR_EDEFAULT;
      case Model2BlocklyPackage.CATEGORY_DEF__SUBCATEGORIES:
        return subcategories != null && !subcategories.isEmpty();
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (name: ");
    result.append(name);
    result.append(", label: ");
    result.append(label);
    result.append(", colour: ");
    result.append(colour);
    result.append(')');
    return result.toString();
  }

} //CategoryDefImpl
