/*
 * generated by Xtext 2.42.0
 */
package io.github.plortinus.model2blockly.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractModel2BlocklyScopeProvider extends DelegatingScopeProvider {
}
