/*
 * generated by Xtext 2.39.0
 */
package io.github.plortinus.model2blockly;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class Model2BlocklyStandaloneSetup extends Model2BlocklyStandaloneSetupGenerated {

	public static void doSetup() {
		new Model2BlocklyStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
