/*
 * generated by Xtext 2.39.0
 */
package io.github.plortinus.model2blockly;

import org.eclipse.xtext.naming.IQualifiedNameProvider;
import io.github.plortinus.model2blockly.naming.Model2BlocklyQualifiedNameProvider;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class Model2BlocklyRuntimeModule extends AbstractModel2BlocklyRuntimeModule {

	@Override
	public Class<? extends IQualifiedNameProvider> bindIQualifiedNameProvider() {
		return Model2BlocklyQualifiedNameProvider.class;
	}
}
