/*
 * generated by Xtext 2.42.0
 */
package io.github.plortinus.model2blockly.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class Model2BlocklyAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("io/github/plortinus/model2blockly/parser/antlr/internal/InternalModel2Blockly.tokens");
	}
}
