/*
 * generated by Xtext 2.42.0
 */
package io.github.plortinus.model2blockly.parser.antlr;

import com.google.inject.Inject;
import io.github.plortinus.model2blockly.parser.antlr.internal.InternalModel2BlocklyParser;
import io.github.plortinus.model2blockly.services.Model2BlocklyGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class Model2BlocklyParser extends AbstractAntlrParser {

	@Inject
	private Model2BlocklyGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalModel2BlocklyParser createParser(XtextTokenStream stream) {
		return new InternalModel2BlocklyParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "DomainModel";
	}

	public Model2BlocklyGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(Model2BlocklyGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
