<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore"
    name="referencesIntegrity"
    nsURI="http://www.example.org/referencesintegrity"
    nsPrefix="referencesintegrity">

  <eClassifiers xsi:type="ecore:EClass" name="Workflow">
    <eAnnotations source="blockly">
      <details key="colour" value="260"/>
      <details key="category" value="References"/>
      <details key="inputsInline" value="false"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="Review workflow">
      <eAnnotations source="ui">
        <details key="widget" value="text"/>
        <details key="label" value="Name"/>
        <details key="order" value="1"/>
        <details key="variant" value="default"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elements"
        lowerBound="1" upperBound="6" eType="#//Element" containment="true">
      <eAnnotations source="ui">
        <details key="widget" value="slot"/>
        <details key="label" value="Elements"/>
        <details key="order" value="2"/>
        <details key="variant" value="default"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EClass" name="Element" abstract="true">
    <eAnnotations source="blockly">
      <details key="colour" value="120"/>
      <details key="category" value="References"/>
      <details key="inputsInline" value="false"/>
    </eAnnotations>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EClass" name="Card" eSuperTypes="#//Element">
    <eAnnotations source="blockly">
      <details key="colour" value="120"/>
      <details key="category" value="References"/>
      <details key="inputsInline" value="false"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cardId"
        iD="true" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="card-1">
      <eAnnotations source="ui">
        <details key="widget" value="text"/>
        <details key="label" value="Card ID"/>
        <details key="order" value="1"/>
        <details key="variant" value="default"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="title"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="Review">
      <eAnnotations source="ui">
        <details key="widget" value="text"/>
        <details key="label" value="Title"/>
        <details key="order" value="2"/>
        <details key="variant" value="default"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outgoing"
        upperBound="3" eType="#//Link" eOpposite="#//Link/source">
      <eAnnotations source="ui">
        <details key="widget" value="reference-select"/>
        <details key="label" value="Outgoing links"/>
        <details key="order" value="3"/>
        <details key="variant" value="default"/>
        <details key="referenceLabelField" value="linkId"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EClass" name="Link" eSuperTypes="#//Element">
    <eAnnotations source="blockly">
      <details key="colour" value="120"/>
      <details key="category" value="References"/>
      <details key="inputsInline" value="false"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="linkId"
        iD="true" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="link-1">
      <eAnnotations source="ui">
        <details key="widget" value="text"/>
        <details key="label" value="Link ID"/>
        <details key="order" value="1"/>
        <details key="variant" value="default"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source"
        lowerBound="1" eType="#//Card" eOpposite="#//Card/outgoing">
      <eAnnotations source="ui">
        <details key="widget" value="reference-select"/>
        <details key="label" value="Source card"/>
        <details key="order" value="2"/>
        <details key="variant" value="default"/>
        <details key="referenceLabelField" value="title"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="Continue">
      <eAnnotations source="ui">
        <details key="widget" value="text"/>
        <details key="label" value="Description"/>
        <details key="order" value="3"/>
        <details key="variant" value="default"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target"
        lowerBound="1" upperBound="2" unique="false" ordered="false" eType="#//Card">
      <eAnnotations source="ui">
        <details key="widget" value="reference-select"/>
        <details key="label" value="Target cards"/>
        <details key="order" value="4"/>
        <details key="variant" value="default"/>
        <details key="referenceLabelField" value="title"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>

</ecore:EPackage>
