/*
 * generated by Xtext 2.39.0
 */
package io.github.plortinus.model2blockly.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class Model2BlocklyUiModule extends AbstractModel2BlocklyUiModule {

	public Model2BlocklyUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
