<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="model2Blockly" nsURI="https://plortinus.github.io/model2blockly/ns/model2blockly"
    nsPrefix="model2Blockly">
  <eClassifiers xsi:type="ecore:EClass" name="DomainModel">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="codeLanguage" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="codeFileExtension" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="runtimeKind" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="workspace" eType="#//WorkspaceConfig"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="categories" upperBound="-1"
        eType="#//CategoryDef" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="classes" upperBound="-1"
        eType="#//ClassDef" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="constraints" upperBound="-1"
        eType="#//ConstraintDef" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="validations" upperBound="-1"
        eType="#//ValidationDef" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CategoryDef">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="label" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="colour" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="subcategories" upperBound="-1"
        eType="#//CategoryDef" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ClassDef">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="abstract" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="output" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outputType" eType="#//ClassDef"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="superClass" eType="#//ClassDef"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="category" eType="#//CategoryDef"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="colour" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="label" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="message0" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tooltip" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="helpUrl" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="inputsInline" eType="#//BoolVal"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="inline" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="codeTemplate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="features" upperBound="-1"
        eType="#//Feature" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Feature">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ui" eType="#//UiOptions"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Attribute" eSuperTypes="#//Feature">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//AttributeType"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="cardinality" eType="#//Cardinality"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="min" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="max" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="imageUrl" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="imageWidth" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="imageHeight" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="imageAlt" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="required" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="unique" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nonUnique" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ordered" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="unordered" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Containment" eSuperTypes="#//Feature">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//ClassDef"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lower" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="upper" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Reference" eSuperTypes="#//Feature">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//ClassDef"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="cardinality" eType="#//Cardinality"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="oppositeName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="required" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="unique" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nonUnique" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ordered" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="unordered" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ValueInput" eSuperTypes="#//Feature">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//ClassDef"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="shadowType" eType="#//ClassDef"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Cardinality">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lower" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="upper" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UiOptions">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="widget" eType="#//UiWidget"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="uiLabel" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="help" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="placeholder" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="group" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="order" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="uiReadonly" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="uiHidden" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="variant" eType="#//UiVariant"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="referenceLabelField" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="UiWidget">
    <eLiterals name="TEXT" literal="text"/>
    <eLiterals name="TEXTAREA" value="1" literal="textarea"/>
    <eLiterals name="NUMBER" value="2" literal="number"/>
    <eLiterals name="SLIDER" value="3" literal="slider"/>
    <eLiterals name="SWITCH" value="4" literal="switch"/>
    <eLiterals name="CHECKBOX" value="5" literal="checkbox"/>
    <eLiterals name="SELECT" value="6" literal="select"/>
    <eLiterals name="RADIO" value="7" literal="radio"/>
    <eLiterals name="COLOR" value="8" literal="color"/>
    <eLiterals name="ANGLE" value="9" literal="angle"/>
    <eLiterals name="IMAGE" value="10" literal="image"/>
    <eLiterals name="REFERENCE_SELECT" value="11" literal="reference-select"/>
    <eLiterals name="SLOT" value="12" literal="slot"/>
    <eLiterals name="EXPRESSION_SLOT" value="13" literal="expression-slot"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="UiVariant">
    <eLiterals name="DEFAULT" literal="default"/>
    <eLiterals name="COMPACT" value="1" literal="compact"/>
    <eLiterals name="PROMINENT" value="2" literal="prominent"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AttributeType"/>
  <eClassifiers xsi:type="ecore:EClass" name="SimpleType" eSuperTypes="#//AttributeType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="typeName" eType="#//SimpleTypeName"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="SimpleTypeName">
    <eLiterals name="string" literal="string"/>
    <eLiterals name="int" value="1" literal="int"/>
    <eLiterals name="boolean" value="2" literal="boolean"/>
    <eLiterals name="float" value="3" literal="float"/>
    <eLiterals name="colour" value="4" literal="colour"/>
    <eLiterals name="angle" value="5" literal="angle"/>
    <eLiterals name="image" value="6" literal="image"/>
    <eLiterals name="label" value="7" literal="label"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EnumType" eSuperTypes="#//AttributeType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="literals" upperBound="-1"
        eType="#//EnumLiteral" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EnumLiteral">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="label" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConstraintDef">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="#//ClassDef"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="predecessor" eType="#//ClassDef"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ValidationDef">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="#//ClassDef"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kind" eType="#//ValidationKind"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="expression" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="message" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ValidationKind">
    <eLiterals name="EXPRESSION" literal="expression"/>
    <eLiterals name="CONDITION" value="1" literal="condition"/>
    <eLiterals name="JS" value="2" literal="js"/>
    <eLiterals name="OCL" value="3" literal="ocl"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WorkspaceConfig">
    <eStructuralFeatures xsi:type="ecore:EReference" name="options" upperBound="-1"
        eType="#//WorkspaceOption" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WorkspaceOption">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StringOption" eSuperTypes="#//WorkspaceOption">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IntOption" eSuperTypes="#//WorkspaceOption">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BoolOption" eSuperTypes="#//WorkspaceOption">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="#//BoolVal"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ObjectOption" eSuperTypes="#//WorkspaceOption">
    <eStructuralFeatures xsi:type="ecore:EReference" name="entries" upperBound="-1"
        eType="#//WorkspaceOption" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="BoolVal">
    <eLiterals name="TRUE" literal="true"/>
    <eLiterals name="FALSE" value="1" literal="false"/>
  </eClassifiers>
</ecore:EPackage>
